=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/xml/dtd/math4u2DTD.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--Hauptelement. Es dient als Wurzel für alle weiteren Knotenelemente.-->
<!ELEMENT math4u2 (head?, body)>
<!--Körper des Dokuments für den eigentlichen Inhalt-->
<!ELEMENT body (location?, title, summary?, keywords?, step+, exercise*)>
<!--Eine einfache Ja-/Nein-Frage-->
<!ELEMENT choice (statement, solution, explanation?)>
<!--Setzen des Layouts-->
<!ELEMENT layout (row+)+>
<!--Gruppe von parallel ausführbaren Plugin-Aktionen-->
<!ELEMENT par (animate | call | par | seq | script)*>
<!--Eine Multiple-Choice-Frage-->
<!ELEMENT selection (description?, choice)+>
<!ATTLIST selection
	mutual CDATA #IMPLIED
>
<!--Gruppe von sequentiell ausführbaren Plugin-Aktionen-->
<!ELEMENT seq (animate | call | par | seq | script)*>
<!ATTLIST seq
	repeat CDATA #IMPLIED
>
<!ELEMENT script ANY>
<!ELEMENT location (#PCDATA)>
<!--Datentyp für formattierbaren (gemischten) Text mit Formeln, Auszeichnungen und Bildern-->
<!ELEMENT title (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Zusammenfassung des Themas-->
<!ELEMENT summary (#PCDATA)>

<!ELEMENT keywords (keyword)*>

<!ELEMENT keyword (#PCDATA)>

<!ELEMENT step (title?, description?, layout?, (par | seq)*)>
<!--Übungen-->
<!ELEMENT exercise (title?, description?, summary?, (seq | par)*, (choice | selection)+)>
<!--Aussage-->
<!ELEMENT statement (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Lösung-->
<!ELEMENT solution (#PCDATA)>
<!--Begründung-->
<!ELEMENT explanation (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Reihe des Layouts-->
<!ELEMENT row (col+)+>
<!ATTLIST row
	perc CDATA #REQUIRED
>
<!--Kopf des Dokuments für nicht sichtbare Definitionen-->
<!ELEMENT head (version, author?, meta*, module*)>
<!--Animation eines bestimmten Attributs eines Moduls-->
<!ELEMENT animate EMPTY>
<!ATTLIST animate
	object CDATA #REQUIRED
	getAction CDATA #IMPLIED
	setAction CDATA #IMPLIED
	parameterName CDATA #REQUIRED
	from CDATA #IMPLIED
	to CDATA #REQUIRED
	by CDATA #IMPLIED
	begin CDATA #IMPLIED
	end CDATA #REQUIRED
	dur CDATA #IMPLIED
	timeFunction CDATA #IMPLIED
>
<!--Aktionsaufruf an ein Modul-->
<!ELEMENT call (param*)>
<!ATTLIST call
	object CDATA #REQUIRED
	action CDATA #REQUIRED
	begin CDATA #IMPLIED
	end CDATA #IMPLIED
	dur CDATA #IMPLIED
>
<!--Stellen einer Frage-->
<!ELEMENT description (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Mathematische Formel: Es ist MathML realisiert, sowie eine Math4u2-Schreibweise. Bei letzeren wird kein Attribut "type" angegeben. Bei "show=" können nun 3 verschiedene Darstellungsarten festgelegt werden. 1.formal z.B. f(x):=a*x. 2. actual z.B. f(x):=2*x (Parameter wird eingesetzt und kann verändert werden). 3. short z.B. f(x)-->
<!ELEMENT formula (#PCDATA | conf)*>
<!ATTLIST formula
	type CDATA #IMPLIED
	show CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
>
<!--Kurzform von formula-->
<!ELEMENT f (#PCDATA | conf)*>
<!ATTLIST f
	bgcolor CDATA #IMPLIED
>
<!--Kurzform von formula show = "short"-->
<!ELEMENT fh (#PCDATA | conf)*>
<!ATTLIST fh
	bgcolor CDATA #IMPLIED
>
<!--Kurzform von formula show="body"-->
<!ELEMENT fb (#PCDATA | conf)*>
<!ATTLIST fb
	bgcolor CDATA #IMPLIED
>
<!--Formeldefinition-->
<!ELEMENT fd (#PCDATA)>
<!ATTLIST fd
	bgcolor CDATA #IMPLIED
	width CDATA #IMPLIED
>
<!ELEMENT conf (#PCDATA)>
<!--Referenz auf andere Abschnitte-->
<!ELEMENT ref (#PCDATA)>
<!ATTLIST ref
	target IDREF #IMPLIED
>
<!--Absatz-->
<!ELEMENT p (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Zeilenumbruch-->
<!ELEMENT br ANY>
<!--Normal betonter Text-->
<!ELEMENT em (#PCDATA)>
<!--Stark betonter Text-->
<!ELEMENT strong (#PCDATA)>
<!--Verweis auf ein Bild-->
<!ELEMENT img EMPTY>
<!ATTLIST img
	src CDATA #REQUIRED
>
<!--Code Text-->
<!ELEMENT code (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Tablulator-->
<!ELEMENT tab ANY>
<!--Kommando bzw. Funktionalität-->
<!ELEMENT command (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Tabelle angelehnt an HTML-->
<!ELEMENT table (tr)+>
<!ATTLIST table
	border CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
>
<!--Unorderd List angelehnt an HTML-->
<!ELEMENT ul (li)+>
<!ELEMENT col EMPTY>
<!ATTLIST col
	perc CDATA #REQUIRED
	name CDATA #REQUIRED
	type CDATA #IMPLIED
>
<!--Versionsnummer des Dokuments-->
<!ELEMENT version (#PCDATA)>
<!--Autor(en) des  des Dokuments-->
<!ELEMENT author (#PCDATA)>
<!--Zusätzliche Meta-Information-->
<!ELEMENT meta EMPTY>
<!ATTLIST meta
	name CDATA #REQUIRED
	content CDATA #REQUIRED
>
<!--Zum Anmelden eines externes Moduls (z. B. von Graphendarstellung, Soundeinbindung oder von selbstgeschriebenen Modulen). Die Module werden in der Datei math4u2/conf/config.properties näher bestimmt. Jedes Modul muß in Java von JPanel abgeleitet sein.-->
<!ELEMENT module EMPTY>
<!ATTLIST module
	class CDATA #REQUIRED
	id ID #REQUIRED
>
<!--Einzelner Parameter für den Aktionsaufruf-->
<!ELEMENT param EMPTY>
<!ATTLIST param
	type CDATA #REQUIRED
	value CDATA #REQUIRED
>
<!ELEMENT tr (td)+>
<!--list item-->
<!ELEMENT li (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Datentyp für formattierbaren (gemischten) Text mit Formeln, Auszeichnungen und Bildern-->
<!ELEMENT td (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!ATTLIST td
	bgcolor CDATA #IMPLIED
>
<!-- Entities -->
<!ENTITY not "&#x000AC;">
<!--/neg /lnot =not sign -->
<!ENTITY ne "&#x02260;">
<!--/ne /neq R: not equal -->
<!ENTITY equals "&#x0003D;">
<!--=equals sign R: -->
<!ENTITY NotEqual "&#x02260;">
<!--alias ISOTECH ne -->
<!ENTITY equiv "&#x02261;">
<!--/equiv R: identical with -->
<!ENTITY le "&#x02264;">
<!-- less equal -->
<!ENTITY ge "&#x02265;">
<!--/geq /ge R: greater-than-or-equal -->
<!ENTITY sub "&#x02282;">
<!--/subset R: subset or is implied by -->
<!ENTITY sup "&#x02283;">
<!--/supset R: superset or implies -->
<!ENTITY nsub "&#x02284;">
<!--not subset -->
<!ENTITY sube "&#x02286;">
<!--/subseteq R: subset, equals -->
<!ENTITY supe "&#x02287;">
<!--/supseteq R: superset, equals -->
<!ENTITY oplus "&#x02295;">
<!--/oplus B: plus sign in circle -->
<!ENTITY otimes "&#x02297;">
<!--/otimes B: multiply sign in circle -->
<!ENTITY perp "&#x022A5;">
<!--/perp R: perpendicular -->
<!ENTITY forall "&#x02200;">
<!--/forall for all -->
<!ENTITY part "&#x02202;">
<!--/partial partial differential -->
<!ENTITY exist "&#x02203;">
<!--/exists at least one exists -->
<!ENTITY nabla "&#x02207;">
<!--/nabla del, Hamilton operator -->
<!ENTITY isin "&#x02208;">
<!--/in R: set membership  -->
<!ENTITY Element "&#x02208;">
<!--/in R: set membership  -->
<!ENTITY notin "&#x02209;">
<!--/notin N: negated set membership -->
<!ENTITY ni "&#x0220B;">
<!--/ni /owns R: contains -->
<!ENTITY prop "&#x0221D;">
<!--/propto R: is proportional to -->
<!ENTITY infin "&#x0221E;">
<!--/infty infinity -->
<!ENTITY ang "&#x02220;">
<!--/angle - angle -->
<!ENTITY and "&#x02227;">
<!--/wedge /land B: logical and -->
<!ENTITY or "&#x02228;">
<!--/vee /lor B: logical or -->
<!ENTITY cap "&#x02229;">
<!--/cap B: intersection -->
<!ENTITY cup "&#x0222A;">
<!--/cup B: union or logical sum -->
<!ENTITY sim "&#x0223C;">
<!--/sim R: similar -->
<!ENTITY cong "&#x02245;">
<!--/cong R: congruent with -->
<!ENTITY asymp "&#x0224D;">
<!--/asymp R: asymptotically equal to -->
<!ENTITY minus "&#x02212;">
<!--B: minus sign -->
<!ENTITY plus "&#x0002B;">
<!--=plus sign B: -->
<!ENTITY plusmn "&#x000B1;">
<!--/pm B: =plus-or-minus sign -->
<!-- Pfeille -->
<!ENTITY larr "&#x02190;">
<!--/leftarrow /gets A: =leftward arrow -->
<!ENTITY rarr "&#x02192;">
<!--/rightarrow /to A: =rightward arrow -->
<!ENTITY uarr "&#x02191;">
<!--/uparrow A: =upward arrow -->
<!ENTITY darr "&#x02193;">
<!--/downarrow A: =downward arrow -->
<!ENTITY harr "&#x02194;">
<!--/leftrightarrow A: l&r arrow -->
<!ENTITY lArr "&#x021D0;">
<!--/Leftarrow A: is implied by -->
<!ENTITY rArr "&#x021D2;">
<!--/Rightarrow A: implies -->
<!ENTITY uArr "&#x021D1;">
<!--/Uparrow A: up dbl arrow -->
<!ENTITY dArr "&#x021D3;">
<!--/Downarrow A: down dbl arrow -->
<!ENTITY hArr "&#x021D4;">
<!--/Leftrightarrow A: l&r dbl arrow -->
<!-- Griechische Zeichen -->
<!ENTITY fnof "&#x00192;">
<!--function of (italic small f) -->
<!ENTITY alpha "&#x003B1;">
<!--/alpha small alpha, Greek -->
<!ENTITY beta "&#x003B2;">
<!--/beta small beta, Greek -->
<!ENTITY chi "&#x003C7;">
<!--/chi small chi, Greek -->
<!ENTITY delta "&#x003B4;">
<!--/delta small delta, Greek -->
<!ENTITY Delta "&#x00394;">
<!--/Delta capital Delta, Greek -->
<!ENTITY epsi "&#x003B5;">
<!--/straightepsilon, small epsilon, Greek -->
<!ENTITY epsiv "&#x0025B;">
<!--/varepsilon -->
<!ENTITY eta "&#x003B7;">
<!--/eta small eta, Greek -->
<!ENTITY gamma "&#x003B3;">
<!--/gamma small gamma, Greek -->
<!ENTITY Gamma "&#x00393;">
<!--/Gamma capital Gamma, Greek -->
<!ENTITY gammad "&#x003DC;">
<!--/digamma -->
<!ENTITY Gammad "&#x003DC;">
<!--capital digamma -->
<!ENTITY iota "&#x003B9;">
<!--/iota small iota, Greek -->
<!ENTITY kappa "&#x003BA;">
<!--/kappa small kappa, Greek -->
<!ENTITY kappav "&#x003F0;">
<!--/varkappa -->
<!ENTITY lambda "&#x003BB;">
<!--/lambda small lambda, Greek -->
<!ENTITY Lambda "&#x0039B;">
<!--/Lambda capital Lambda, Greek -->
<!ENTITY mu "&#x003BC;">
<!--/mu small mu, Greek -->
<!ENTITY nu "&#x003BD;">
<!--/nu small nu, Greek -->
<!ENTITY omega "&#x003C9;">
<!--/omega small omega, Greek -->
<!ENTITY Omega "&#x003A9;">
<!--/Omega capital Omega, Greek -->
<!ENTITY phi "&#x003C6;">
<!--/straightphi - small phi, Greek -->
<!ENTITY Phi "&#x003A6;">
<!--/Phi capital Phi, Greek -->
<!ENTITY phiv "&#x003D5;">
<!--/varphi - curly or open phi -->
<!ENTITY pi "&#x003C0;">
<!--/pi small pi, Greek -->
<!ENTITY Pi "&#x003A0;">
<!--/Pi capital Pi, Greek -->
<!ENTITY piv "&#x003D6;">
<!--/varpi -->
<!ENTITY psi "&#x003C8;">
<!--/psi small psi, Greek -->
<!ENTITY Psi "&#x003A8;">
<!--/Psi capital Psi, Greek -->
<!ENTITY rho "&#x003C1;">
<!--/rho small rho, Greek -->
<!ENTITY rhov "&#x003F1;">
<!--/varrho -->
<!ENTITY sigma "&#x003C3;">
<!--/sigma small sigma, Greek -->
<!ENTITY Sigma "&#x003A3;">
<!--/Sigma capital Sigma, Greek -->
<!ENTITY sigmav "&#x003C2;">
<!--/varsigma -->
<!ENTITY tau "&#x003C4;">
<!--/tau small tau, Greek -->
<!ENTITY theta "&#x003B8;">
<!--/theta straight theta, small theta, Greek -->
<!ENTITY Theta "&#x00398;">
<!--/Theta capital Theta, Greek -->
<!ENTITY thetav "&#x003D1;">
<!--/vartheta - curly or open theta -->
<!ENTITY upsi "&#x003C5;">
<!--/upsilon small upsilon, Greek -->
<!ENTITY Upsi "&#x003D2;">
<!--/Upsilon capital Upsilon, Greek -->
<!ENTITY xi "&#x003BE;">
<!--/xi small xi, Greek -->
<!ENTITY Xi "&#x0039E;">
<!--/Xi capital Xi, Greek -->
<!ENTITY zeta "&#x003B6;">
<!--/zeta small zeta, Greek -->
<!ENTITY Upsilon "&#x003D2;">
<!--alias ISOGRK3 Upsi -->
<!ENTITY upsilon "&#x003C5;">
<!--alias ISOGRK3 upsi -->

=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/doc/hilfe/03Objekte/03.04Affine-Objekte.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE math4u2 PUBLIC "-//FH Augsburg//DTD Math4u2//DE" "http://www.math4u2.de/xml/dtd/math4u2DTD.dtd">
<math4u2>
	<head>
		<version>2.0</version>
		<author>Stefan Fenn, Erich Seifert, Prof. Dr. Maximilian Weiß</author>
		<module id="main" class="ShowMeGraph"/>
	</head>
	<body>
		<location>3. Daten, Funktionen, Objekte, Graphen/3.4 Affine Objekte</location>
		<title>3.4 Affine Objekte</title>
		<step>
			<title>3.4 Affine Objekte</title>
			<description>			
Die folgende Tabelle gibt einen Überblick über die affinen Objekte
Anschließend sind sie in der gleichen Reihenfolge ausführlich beschrieben.
<p/>
<table>
	<tr>
		<td bgcolor="#F4C86C"><strong>Objekt</strong></td>
		<td bgcolor="#F4C86C"><strong>Eigenschaften</strong></td>
	</tr>
	<tr>
		<td><code>punkt(xf,yf)</code></td>
		<td>
Punkt mit den Koordeinatenfunktionen <code>xf</code> und <code>yf</code>.
<br/>Die beiden Koordinatenfunktoinen <code>xf</code> und <code>yf</code> sind nullstellige Funktionen.
<br/>Methoden:
<br/><code>.x</code> : x-Koordinate (nullstellige Funktion)
<br/><code>.y</code> : y-Koordinate (nullstellige Funktion)
<br/><code>.r</code> : Ortsvektor (zweidimensionaler Vektor)
<br/>Interaktion:
<br/>Der Punkt kann mit der Maus bewegt werden. Dadurch werden
<br/>die Koordinaten des Punkts verändert.			
		</td>
	</tr>	
	<tr>
		<td><code>marker(xf,yf)</code></td>
		<td>
Markierung mit den Koordinatenfunktionen <code>xf</code> und <code>yf</code>.
<br/>Anders als beim Punkt wird der Name nicht angezeigt,
<br/>eine Markierung kann nicht mit der Maus bewegt werden.			
		</td>
	</tr>	
	<tr>
		<td><code>strecke(p1,p2)</code></td>
		<td>
Verbindungsstrecke der Punkte <code>p1</code> und <code>p2</code>.
<br/>Methoden:
<br/><code>.begin</code> : Startpunkt der Strecke
<br/><code>.ende</code> : Endpunkt der Strecke						
		</td>
	</tr>	
	<tr>
		<td><code>gerade(p,v)</code></td>
		<td>
Gerade durch den Punkt <code>p</code> mit dem Richtungsvektor <code>v</code>.
<br/><code>v</code> ist eine nullstellige Funktion, die als Ergebnis einen zweidimensionalen
<br/>Vektor liefert.
<br/>Methoden:
<br/><code>.start</code> : Punkt <code>p</code> auf der Gerade
<br/><code>.richtung</code> : Richtungsvektor <code>v</code> der Gerade					
		</td>
	</tr>	
	<tr>
		<td><code>kreis(p,r)</code></td>
		<td>
Kreis mit Mittelpunkt <code>p</code> und Radius <code>r</code>.
<br/><code>r</code> ist eine nullstellige Funktion, die als Ergebnis eine Zahl liefert.
<br/>Methoden:
<br/><code>.mitte</code> : Mittelpunkt
<br/><code>.radius</code> : Radius
<br/><code>.flaeche</code> : Flächeninhalt					
		</td>
	</tr>	
	<tr>
		<td><code>winkel(ps, v1, v2, r)</code></td>
		<td>
Winkel mit Scheitelpunkt <code>ps</code> und den beiden
<br/>Richtungen <code>v1</code> und <code>v2</code>.
<br/><code>r</code> legt den Radius fest, mit dem der Winkel gezeichnet wird.
<br/>Methoden:
<br/><code>.scheitelpunkt</code> : Scheitelpunkt des Winkels					
		</td>
	</tr>	
	<tr>
		<td><code>kurve(t, s, e, fx(t), fy(t))</code></td>
		<td>
Parametrisierte Kurve mit Kurvenparameter <code>t</code>.
<br/><code>s</code> und <code>e</code> sind zwei nullstellige Funktionen, sie liefern Start- und
<br/>Endwert für das Parameterintervall.
<br/><code>fx(t)</code> und <code>fy(t)</code> sind die Koordinatenfunktionen für die x- bzw. y-
<br/>Koordinate.
<br/>Methoden:
<br/><code>.min</code> : Untere Grenze des Parameterintervalls
<br/><code>.max</code> : Obere Grenze des Parameterintervalls
<br/><code>.x</code> : x-Koordinatenfunktion (einstellige Funktion)
<br/><code>.y</code> : y-Koordinatenfunktion (einstellige Funktion)					
		</td>
	</tr>	
	<tr>
		<td><code>bezier(p1,p2,p3,p4)</code></td>
		<td>
Kubische Bezier-Kurve mit den Steuerpunkten <code>p1</code>, <code>p2</code>, <code>p3</code>, <code>p4</code>.
<br/>Startet bei <code>p1</code> mit Richtung auf <code>p2</code> zu, endet bei <code>p4</code>, kommt dort mit
<br/>der Richtung von <code>p3</code> her an.
<br/>Methoden:
<br/><code>.p1</code> : Startpunkt
<br/><code>.p2</code> : Steuerpunkt für Startrichtung
<br/><code>.p3</code> : Steuerpunkt für Endrichtung
<br/><code>.p4</code> : Endpunkt				
		</td>
	</tr>	
	<tr>
		<td><code>kurvenzug({e1, e2, ... })</code></td>
		<td>
Kurvenzug, der entsteht, wenn die Elemente <code>e1</code>, <code>e2</code>, ... durch
<br/>Strecken verbunden werden. Die Elemente <code>e1</code>, <code>e2</code>, ... können
<br/>sein: Punkte, Strecken, parametrisierte Kurven oder Bezier-Kurven.
		</td>
	</tr>	
	<tr>
		<td><code>flaeche({e1, e2, ... })</code></td>
		<td>
Fläche, deren Begrenzung durch eine Liste {<code>e1</code>, <code>e2</code>, ...} von Elementen
<br/>gegeben ist. Die Elemente <code>e1</code>, <code>e2</code>, ... können sein:
<br/>Punkte, Strecken, parametrisierte Kurven oder Bezier-Kurven
<br/>sein.					
		</td>
	</tr>	
	<tr>
		<td><code>pfeil(p,v)</code></td>
		<td>
Repräsentant des Vektors <code>v</code> mit Aufpunkt <code>p</code>.
<br/><code>v</code> ist dabei ein zweidimensionaler Vektor bzw. eine Funktion, die
<br/>als Ergebnis einen zweidimensionalen Vektor liefert.
<br/>Methoden:
<br/><code>.start</code> : Startpunkt des Pfeils
<br/><code>.richtung</code> : Richtungsvektor des Pfeils
<br/>Interaktion:
<br/>Die Pfeilspitze kann mit der Maus bewegt werden. Dadurch werden
<br/>die Koordinaten des Vektors <code>v</code> verändert.			
		</td>
	</tr>											
</table>

<p/><strong>Maus-Position als vordefinierter Punkt</strong>
<br/>Die aktuelle Maus-Position ist als Punkt mit dem Namen <code>mouse</code> vordefiniert.
Durch Auswahl des Elements "Mauskoordinaten anzeigen" im Menü der Steuerleiste kann eine
Detailsicht erzeugt werden, die immer die aktuellen Koordinaten der Maus anzeigt.
			</description>
		</step>
	</body>
</math4u2>

=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/doc/hilfe/03Objekte/03.04.10Flaeche.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE math4u2 PUBLIC "-//FH Augsburg//DTD Math4u2//DE" "http://www.math4u2.de/xml/dtd/math4u2DTD.dtd">
<math4u2>
	<head>
		<version>2.0</version>
		<author>Stefan Fenn, Erich Seifert, Prof. Dr. Maximilian Weiß</author>
		<module id="main" class="ShowMeGraph"/>
	</head>
	<body>
		<location>3. Daten, Funktionen, Objekte, Graphen/3.4 Affine Objekte</location>
		<title>3.4.10 Fläche</title>
		<step>
			<title>3.4.10 Fläche</title>
			<description>
Die Regeln bei der Definition einer Fläche sind zunächst die gleichen wie die bei einem Kurvenzug.
Zusätzlich wird der Endpunkt des letzten Elements mit dem Startpunkt des ersten Elements durch eine
Strecke verbunden (falls diese Punkte nicht identisch sind). Beim Zeichnen wird die so eingeschlossene
Fläche mit der gewählten Farbe ausgefüllt.	

<p/><strong>Fläche definieren</strong>
<br/><code>dreieck:=flaeche({ punkt(0,0), punkt(4,-1), punkt(3,7) })</code>
<br/>definiert ein Dreieck.
<p/>Ansonsten gelten die gleichen Regeln wie bei einem Kurvenzug.						
			</description>
		</step>
	</body>
</math4u2>

=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/doc/hilfe/03Objekte/03.04.07Parametrisierte-Kurve.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE math4u2 PUBLIC "-//FH Augsburg//DTD Math4u2//DE" "http://www.math4u2.de/xml/dtd/math4u2DTD.dtd">
<math4u2>
	<head>
		<version>2.0</version>
		<author>Stefan Fenn, Erich Seifert, Prof. Dr. Maximilian Weiß</author>
		<module id="main" class="ShowMeGraph"/>
	</head>
	<body>
		<location>3. Daten, Funktionen, Objekte, Graphen/3.4 Affine Objekte</location>
		<title>3.4.07 Parametrisierte Kurve</title>
		<step>
			<title>3.4.7 Parametrisierte Kurve</title>
			<description>			
<strong>Parametrisierte Kurve definieren</strong>
<br/>Eine Kurve wird durch Angabe von 5 Parametern wie bei
<br/><code>kurve1:=kurve(t,0,2*pi, cos(t), sin(t)+1)</code> definiert.
<br/>Dabei ist der erste Parameter (hier: <code>t</code>, allgemein: ein Bezeichner) der sogenannte Kurvenparameter,
er wird oft als Zeit interpretiert. Die beiden folgenden Parameter legen das 
Intervall fest, das der Kurvenparameter durchläuf. Hier legen die beiden 
Parameter <code>0</code> und <code>2*pi</code> das Intervall fest.

<p/>Zuletzt folgen die beiden Koordinatenfunktionen, zuerst für die x-Koordinate, 
dann für die y-Koordinate. Sie sind einstellige Funktionen, ihre 
Funktionsvariable ist der vereinbarte Kurvenparameter. Hier sind als 
Koordinatenfunktoinen die beiden Funktionen <code>cos(t)</code> und <code>sin(t)+1</code> vereinbart.
<code>kurve1</code> definiert die Kreislinie eines Kreises mit Radius 1 und Mittelpunkt bei (0,1).

<p/><strong>Detailsicht</strong>
<p/><img src="math4u2/doc/images/objekte/kurve-detail01.jpg"/>

<p/><strong>Methoden einer Kurve</strong>
<br/>Zu einer Kurve <code>k</code> liefert
<br/><code>k.min </code><tab/> die untere Grenze des Parameterintervalls,
<br/><code>k.max </code><tab/> die obere Grenze des Parameterintervalls,
<br/><code>k.x   </code><tab/> die Koordinatenfunktion der x-Koordinate (einstellige Funktion) und
<br/><code>k.y   </code><tab/> die Koordinatenfunktion der y-Koordinate (einstellige Funktion).

<p/><strong>Beispiel:</strong> Ausschnitt aus einem Funktionsgraphen als 
parametrisierte Kurve
<p/><img src="math4u2/doc/images/objekte/kurve01.jpg"/>
			</description>
		</step>
	</body>
</math4u2>

=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/xml/Numerik/Nichtlineare Gleichungen/sekantenverfahren.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Max Weiß (Fachhochschule Augsburg) -->
<!DOCTYPE math4u2 PUBLIC "-//FH Augsburg//DTD Math4u2//DE" "dtd/math4u2DTD.dtd">
<math4u2>
	<head>
		<version>2.0</version>
		<author>Dr. Weiss</author>
		<module id="main" class="ShowMeGraph"/>
	</head>
	<body>
		<location>Numerik/Nichtlineare Gleichungen</location>
		<title>Sekantenverfahren</title>
		<summary/>
		<step>
			<layout>
				<row perc="70">
					<col perc="100" name="da"/>
				</row>
				<row perc="30">
					<col perc="100" name="intervalle"/>
				</row>
			</layout>
			<seq>
				<script>
		          expand( left = false; right = false );
						    newObject( def = da.xMin := -2);
						    newObject( def = da.xMax := 8);
						    newObject( def = da.yMin := -2);
						    newObject( def = da.yMax := 3);
						    newObject( def = intervalle.xMin := da.xMin);
						    newObject( def = intervalle.xMax := da.xMax);
						    
						    newObject( def = intervalle.yMin := -1);
						    newObject( def = intervalle.yMax := 8);
						    da.setTitle( title = "Funktion");
						    intervalle.setTitle( title = "Konvergenz");
						    newObject( def = a0:= 2);
						    newObject( def = a1 := 4);
						    newObject( def = mey:= vektor( {0,-1} ) );
						    newObject( def = deltay:= 0.1*(da.yMax-da.yMin ) ; hide = true );
						    newObject( def = mey2:= vektor( {0, -deltay } ) );
						    //newObject( def = pp0:=pfeil( punkt(a0, deltay), mey2 ); color = blue; target = da );
						    
						    newObject( def = pos:= a0; hide = true );
						    newObject( def = gy := gerade( punkt( pos, 0 ) , mey ) ; color = blue; linestyle = dot; target = da );
						    intervalle.addGraph( name = gy );
						    newObject( def = ta0:=text( punkt(a0, 0), "<f>x[0]</f>", C_N ); bordercolor = blue; target = da );

						    newObject( def = p0:=pfeil( punkt(a0, 1), mey ); color = blue; target = intervalle );
						    

						    
						    newObject( def = fl(x):=-0.2*(x-3)*(x+1)^2; color = red);
						    //newObject( def = graphl:=kurve(t,-20, 1.5, t, fl(t)); color = red; target = da );
						    newObject( def = fr(x):=-(x+5.4)/(x-10)-2; color = blue);
						    //newObject( def = graphr:=kurve(t,1.5, 20, t, fr(t)); color = red; target = da );   
						    newObject( def = f(x):=cond( x-1.5, fl(x), fr(x) ) ; color = red; target = da );
						    
						    
						    
		      </script>
			</seq>
		</step>
		<step>
			<seq>
				<script>    
				// zweiten x-Wert markieren
				newObject( def = a1 := 4 );
				newObject( def = pos:= a1 );	
				
				//newObject( def = pp1:=pfeil( punkt(a1, deltay), mey2 ); color = blue; target = da );
				newObject( def = p1:=pfeil( punkt(a1, 2), mey ); color = blue; target = intervalle );
				newObject( def = ta1:=text( punkt(a1, 0), "<f>x[1]</f>", C_N ); bordercolor = blue; target = da );
					   
		      </script>
			</seq>
		</step>
		<step>
		</step>
		<step>
			<seq>
				<script>  
				// sekante Zeichnen
				newObject( def = pos := 1000);
				newObject( def = g0:= marker( a0, fr(a0) ) ; target = da );
				newObject( def = g1:= marker( a1, fr(a1) ) ; target = da );
					  
				newObject( def = sec := gerade( g0, g0.r-g1.r ); target = da );   
					   
		      </script>
			</seq>
		</step>
		<step>
			<seq>
				<script>  
				//Schnittpunkt mit x-Achse markieren
				//deleteObject( name = pp0 );
				//deleteObject( name = pp1 );
				newObject( def = a2 := a0-fr(a0)*(a0-a1)/(fr(a0)-fr(a1)) );
				newObject( def = pos:= a2 );	
				newObject( def = g20:= marker( a2, 0 ); color = blue; target = da );
				
	   
		      </script>
			</seq>
		</step>
		<step>
		   <description><f>x[2] = x[0]-fr(x[0])*(x[0]-x[1])/(fr(x[0])-fr(x[1]))</f>
		   </description>
		   <seq>
		      <script>
		          newObject( def = p2:=pfeil( punkt(a2,3), mey ); color = blue; target = intervalle );
							newObject( def = ta2:=text( punkt(a2, 0), "<f>x[2]</f>", C_N ); bordercolor = blue; target = da );
							deleteObject( name = g20 );
				
		      </script>
		   </seq>
		</step>
		<step>
		   <seq>
		      <script>
		      newObject( def = g2:= marker( a2, fr(a2) ) ; target = da );	    
				newObject( def = sec := gerade( g1, g1.r-g2.r ); target = da );  
				deleteObject( name = ta0, g0 );
				newObject( def = a3 := a1-fr(a1)*(a1-a2)/(fr(a1)-fr(a2)) );
				newObject( def = g30:= marker( a3, 0); color = blue; target = da );
		           
		      </script>
		   </seq>
		</step>
		<step>
			<seq>
				<script>  
				deleteObject( name = g30);				
				newObject( def = pos:= a3 );	
				newObject( def = p3:=pfeil( punkt(a3, 4), mey ); color = blue; target = intervalle );
				newObject( def = ta3:=text( punkt(a3, 0), "<f>x[3]</f>", C_N ); bordercolor = blue; target = da );

		   
		      </script>
			</seq>
		</step>
		<step>
			<seq>
				<script>  
				deleteObject( name = ta1, ta2, ta3, sec, g2 );
				//deleteObject( name = pp3 );
				//newObject( def = g3:= punkt( a3, fr(a3) ) ; target = da );	  
				//newObject( def = sec := gerade( g2, g2.r-g3.r ); target = da );  
				deleteObject( name = g1 ); 
				newObject( def = a4 := a2-fr(a2)*(a2-a3)/(fr(a2)-fr(a3)) );
				newObject( def = pos:= a4 );	
				newObject( def = p4:=pfeil( punkt(a4, 5), mey ); color = blue; target = intervalle );
				newObject( def = ta4:= text( punkt(a4, 0), "<f>x[4]</f>", C_N ); bordercolor = blue; target = da );
				//newObject( def = pp4:=pfeil( punkt(a4, deltay), mey2 ); color = blue; target = da );
		      </script>
			</seq>
		</step>
		<step>
			<seq>
				<script>  
				deleteObject( name = ta4);
				newObject( def = a5 := a3-fr(a3)*(a3-a4)/(fr(a3)-fr(a4)) );
				newObject( def = pos:= a5 );	
				newObject( def = p5:=pfeil( punkt(a5, 6), mey ); color = blue; target = intervalle );
				newObject( def = ta5:= text( punkt(a5, 0), "<f>x[5]</f>", C_N ); bordercolor = blue; target = da );

		      </script>
			</seq>
		</step>
		<step>
			<seq>
				<script>  
				deleteObject( name = ta5);
				
				newObject( def = a6 := a4-fr(a4)*(a4-a5)/(fr(a4)-fr(a5)) );
				newObject( def = pos:= a6 );	
				newObject( def = p6:=pfeil( punkt(a6, 7), mey ); color = blue; target = intervalle );
				newObject( def = ta6:= text( punkt(a6, 0), "<f>x[6]</f>", C_N ); bordercolor = blue; target = da );

		      </script>
			</seq>
		</step>


					</body>
</math4u2>
