=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/xml/dtd/math4u2DTD.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--Hauptelement. Es dient als Wurzel für alle weiteren Knotenelemente.-->
<!ELEMENT math4u2 (head?, body)>
<!--Körper des Dokuments für den eigentlichen Inhalt-->
<!ELEMENT body (location?, title, summary?, keywords?, step+, exercise*)>
<!--Eine einfache Ja-/Nein-Frage-->
<!ELEMENT choice (statement, solution, explanation?)>
<!--Setzen des Layouts-->
<!ELEMENT layout (row+)+>
<!--Gruppe von parallel ausführbaren Plugin-Aktionen-->
<!ELEMENT par (animate | call | par | seq | script)*>
<!--Eine Multiple-Choice-Frage-->
<!ELEMENT selection (description?, choice)+>
<!ATTLIST selection
	mutual CDATA #IMPLIED
>
<!--Gruppe von sequentiell ausführbaren Plugin-Aktionen-->
<!ELEMENT seq (animate | call | par | seq | script)*>
<!ATTLIST seq
	repeat CDATA #IMPLIED
>
<!ELEMENT script ANY>
<!ELEMENT location (#PCDATA)>
<!--Datentyp für formattierbaren (gemischten) Text mit Formeln, Auszeichnungen und Bildern-->
<!ELEMENT title (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Zusammenfassung des Themas-->
<!ELEMENT summary (#PCDATA)>

<!ELEMENT keywords (keyword)*>

<!ELEMENT keyword (#PCDATA)>

<!ELEMENT step (title?, description?, layout?, (par | seq)*)>
<!--Übungen-->
<!ELEMENT exercise (title?, description?, summary?, (seq | par)*, (choice | selection)+)>
<!--Aussage-->
<!ELEMENT statement (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Lösung-->
<!ELEMENT solution (#PCDATA)>
<!--Begründung-->
<!ELEMENT explanation (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Reihe des Layouts-->
<!ELEMENT row (col+)+>
<!ATTLIST row
	perc CDATA #REQUIRED
>
<!--Kopf des Dokuments für nicht sichtbare Definitionen-->
<!ELEMENT head (version, author?, meta*, module*)>
<!--Animation eines bestimmten Attributs eines Moduls-->
<!ELEMENT animate EMPTY>
<!ATTLIST animate
	object CDATA #REQUIRED
	getAction CDATA #IMPLIED
	setAction CDATA #IMPLIED
	parameterName CDATA #REQUIRED
	from CDATA #IMPLIED
	to CDATA #REQUIRED
	by CDATA #IMPLIED
	begin CDATA #IMPLIED
	end CDATA #REQUIRED
	dur CDATA #IMPLIED
	timeFunction CDATA #IMPLIED
>
<!--Aktionsaufruf an ein Modul-->
<!ELEMENT call (param*)>
<!ATTLIST call
	object CDATA #REQUIRED
	action CDATA #REQUIRED
	begin CDATA #IMPLIED
	end CDATA #IMPLIED
	dur CDATA #IMPLIED
>
<!--Stellen einer Frage-->
<!ELEMENT description (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Mathematische Formel: Es ist MathML realisiert, sowie eine Math4u2-Schreibweise. Bei letzeren wird kein Attribut "type" angegeben. Bei "show=" können nun 3 verschiedene Darstellungsarten festgelegt werden. 1.formal z.B. f(x):=a*x. 2. actual z.B. f(x):=2*x (Parameter wird eingesetzt und kann verändert werden). 3. short z.B. f(x)-->
<!ELEMENT formula (#PCDATA | conf)*>
<!ATTLIST formula
	type CDATA #IMPLIED
	show CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
>
<!--Kurzform von formula-->
<!ELEMENT f (#PCDATA | conf)*>
<!ATTLIST f
	bgcolor CDATA #IMPLIED
>
<!--Kurzform von formula show = "short"-->
<!ELEMENT fh (#PCDATA | conf)*>
<!ATTLIST fh
	bgcolor CDATA #IMPLIED
>
<!--Kurzform von formula show="body"-->
<!ELEMENT fb (#PCDATA | conf)*>
<!ATTLIST fb
	bgcolor CDATA #IMPLIED
>
<!--Formeldefinition-->
<!ELEMENT fd (#PCDATA)>
<!ATTLIST fd
	bgcolor CDATA #IMPLIED
	width CDATA #IMPLIED
>
<!ELEMENT conf (#PCDATA)>
<!--Referenz auf andere Abschnitte-->
<!ELEMENT ref (#PCDATA)>
<!ATTLIST ref
	target IDREF #IMPLIED
>
<!--Absatz-->
<!ELEMENT p (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Zeilenumbruch-->
<!ELEMENT br ANY>
<!--Normal betonter Text-->
<!ELEMENT em (#PCDATA)>
<!--Stark betonter Text-->
<!ELEMENT strong (#PCDATA)>
<!--Verweis auf ein Bild-->
<!ELEMENT img EMPTY>
<!ATTLIST img
	src CDATA #REQUIRED
>
<!--Code Text-->
<!ELEMENT code (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Tablulator-->
<!ELEMENT tab ANY>
<!--Kommando bzw. Funktionalität-->
<!ELEMENT command (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Tabelle angelehnt an HTML-->
<!ELEMENT table (tr)+>
<!ATTLIST table
	border CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
>
<!--Unorderd List angelehnt an HTML-->
<!ELEMENT ul (li)+>
<!ELEMENT col EMPTY>
<!ATTLIST col
	perc CDATA #REQUIRED
	name CDATA #REQUIRED
	type CDATA #IMPLIED
>
<!--Versionsnummer des Dokuments-->
<!ELEMENT version (#PCDATA)>
<!--Autor(en) des  des Dokuments-->
<!ELEMENT author (#PCDATA)>
<!--Zusätzliche Meta-Information-->
<!ELEMENT meta EMPTY>
<!ATTLIST meta
	name CDATA #REQUIRED
	content CDATA #REQUIRED
>
<!--Zum Anmelden eines externes Moduls (z. B. von Graphendarstellung, Soundeinbindung oder von selbstgeschriebenen Modulen). Die Module werden in der Datei math4u2/conf/config.properties näher bestimmt. Jedes Modul muß in Java von JPanel abgeleitet sein.-->
<!ELEMENT module EMPTY>
<!ATTLIST module
	class CDATA #REQUIRED
	id ID #REQUIRED
>
<!--Einzelner Parameter für den Aktionsaufruf-->
<!ELEMENT param EMPTY>
<!ATTLIST param
	type CDATA #REQUIRED
	value CDATA #REQUIRED
>
<!ELEMENT tr (td)+>
<!--list item-->
<!ELEMENT li (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Datentyp für formattierbaren (gemischten) Text mit Formeln, Auszeichnungen und Bildern-->
<!ELEMENT td (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!ATTLIST td
	bgcolor CDATA #IMPLIED
>
<!-- Entities -->
<!ENTITY not "&#x000AC;">
<!--/neg /lnot =not sign -->
<!ENTITY ne "&#x02260;">
<!--/ne /neq R: not equal -->
<!ENTITY equals "&#x0003D;">
<!--=equals sign R: -->
<!ENTITY NotEqual "&#x02260;">
<!--alias ISOTECH ne -->
<!ENTITY equiv "&#x02261;">
<!--/equiv R: identical with -->
<!ENTITY le "&#x02264;">
<!-- less equal -->
<!ENTITY ge "&#x02265;">
<!--/geq /ge R: greater-than-or-equal -->
<!ENTITY sub "&#x02282;">
<!--/subset R: subset or is implied by -->
<!ENTITY sup "&#x02283;">
<!--/supset R: superset or implies -->
<!ENTITY nsub "&#x02284;">
<!--not subset -->
<!ENTITY sube "&#x02286;">
<!--/subseteq R: subset, equals -->
<!ENTITY supe "&#x02287;">
<!--/supseteq R: superset, equals -->
<!ENTITY oplus "&#x02295;">
<!--/oplus B: plus sign in circle -->
<!ENTITY otimes "&#x02297;">
<!--/otimes B: multiply sign in circle -->
<!ENTITY perp "&#x022A5;">
<!--/perp R: perpendicular -->
<!ENTITY forall "&#x02200;">
<!--/forall for all -->
<!ENTITY part "&#x02202;">
<!--/partial partial differential -->
<!ENTITY exist "&#x02203;">
<!--/exists at least one exists -->
<!ENTITY nabla "&#x02207;">
<!--/nabla del, Hamilton operator -->
<!ENTITY isin "&#x02208;">
<!--/in R: set membership  -->
<!ENTITY Element "&#x02208;">
<!--/in R: set membership  -->
<!ENTITY notin "&#x02209;">
<!--/notin N: negated set membership -->
<!ENTITY ni "&#x0220B;">
<!--/ni /owns R: contains -->
<!ENTITY prop "&#x0221D;">
<!--/propto R: is proportional to -->
<!ENTITY infin "&#x0221E;">
<!--/infty infinity -->
<!ENTITY ang "&#x02220;">
<!--/angle - angle -->
<!ENTITY and "&#x02227;">
<!--/wedge /land B: logical and -->
<!ENTITY or "&#x02228;">
<!--/vee /lor B: logical or -->
<!ENTITY cap "&#x02229;">
<!--/cap B: intersection -->
<!ENTITY cup "&#x0222A;">
<!--/cup B: union or logical sum -->
<!ENTITY sim "&#x0223C;">
<!--/sim R: similar -->
<!ENTITY cong "&#x02245;">
<!--/cong R: congruent with -->
<!ENTITY asymp "&#x0224D;">
<!--/asymp R: asymptotically equal to -->
<!ENTITY minus "&#x02212;">
<!--B: minus sign -->
<!ENTITY plus "&#x0002B;">
<!--=plus sign B: -->
<!ENTITY plusmn "&#x000B1;">
<!--/pm B: =plus-or-minus sign -->
<!-- Pfeille -->
<!ENTITY larr "&#x02190;">
<!--/leftarrow /gets A: =leftward arrow -->
<!ENTITY rarr "&#x02192;">
<!--/rightarrow /to A: =rightward arrow -->
<!ENTITY uarr "&#x02191;">
<!--/uparrow A: =upward arrow -->
<!ENTITY darr "&#x02193;">
<!--/downarrow A: =downward arrow -->
<!ENTITY harr "&#x02194;">
<!--/leftrightarrow A: l&r arrow -->
<!ENTITY lArr "&#x021D0;">
<!--/Leftarrow A: is implied by -->
<!ENTITY rArr "&#x021D2;">
<!--/Rightarrow A: implies -->
<!ENTITY uArr "&#x021D1;">
<!--/Uparrow A: up dbl arrow -->
<!ENTITY dArr "&#x021D3;">
<!--/Downarrow A: down dbl arrow -->
<!ENTITY hArr "&#x021D4;">
<!--/Leftrightarrow A: l&r dbl arrow -->
<!-- Griechische Zeichen -->
<!ENTITY fnof "&#x00192;">
<!--function of (italic small f) -->
<!ENTITY alpha "&#x003B1;">
<!--/alpha small alpha, Greek -->
<!ENTITY beta "&#x003B2;">
<!--/beta small beta, Greek -->
<!ENTITY chi "&#x003C7;">
<!--/chi small chi, Greek -->
<!ENTITY delta "&#x003B4;">
<!--/delta small delta, Greek -->
<!ENTITY Delta "&#x00394;">
<!--/Delta capital Delta, Greek -->
<!ENTITY epsi "&#x003B5;">
<!--/straightepsilon, small epsilon, Greek -->
<!ENTITY epsiv "&#x0025B;">
<!--/varepsilon -->
<!ENTITY eta "&#x003B7;">
<!--/eta small eta, Greek -->
<!ENTITY gamma "&#x003B3;">
<!--/gamma small gamma, Greek -->
<!ENTITY Gamma "&#x00393;">
<!--/Gamma capital Gamma, Greek -->
<!ENTITY gammad "&#x003DC;">
<!--/digamma -->
<!ENTITY Gammad "&#x003DC;">
<!--capital digamma -->
<!ENTITY iota "&#x003B9;">
<!--/iota small iota, Greek -->
<!ENTITY kappa "&#x003BA;">
<!--/kappa small kappa, Greek -->
<!ENTITY kappav "&#x003F0;">
<!--/varkappa -->
<!ENTITY lambda "&#x003BB;">
<!--/lambda small lambda, Greek -->
<!ENTITY Lambda "&#x0039B;">
<!--/Lambda capital Lambda, Greek -->
<!ENTITY mu "&#x003BC;">
<!--/mu small mu, Greek -->
<!ENTITY nu "&#x003BD;">
<!--/nu small nu, Greek -->
<!ENTITY omega "&#x003C9;">
<!--/omega small omega, Greek -->
<!ENTITY Omega "&#x003A9;">
<!--/Omega capital Omega, Greek -->
<!ENTITY phi "&#x003C6;">
<!--/straightphi - small phi, Greek -->
<!ENTITY Phi "&#x003A6;">
<!--/Phi capital Phi, Greek -->
<!ENTITY phiv "&#x003D5;">
<!--/varphi - curly or open phi -->
<!ENTITY pi "&#x003C0;">
<!--/pi small pi, Greek -->
<!ENTITY Pi "&#x003A0;">
<!--/Pi capital Pi, Greek -->
<!ENTITY piv "&#x003D6;">
<!--/varpi -->
<!ENTITY psi "&#x003C8;">
<!--/psi small psi, Greek -->
<!ENTITY Psi "&#x003A8;">
<!--/Psi capital Psi, Greek -->
<!ENTITY rho "&#x003C1;">
<!--/rho small rho, Greek -->
<!ENTITY rhov "&#x003F1;">
<!--/varrho -->
<!ENTITY sigma "&#x003C3;">
<!--/sigma small sigma, Greek -->
<!ENTITY Sigma "&#x003A3;">
<!--/Sigma capital Sigma, Greek -->
<!ENTITY sigmav "&#x003C2;">
<!--/varsigma -->
<!ENTITY tau "&#x003C4;">
<!--/tau small tau, Greek -->
<!ENTITY theta "&#x003B8;">
<!--/theta straight theta, small theta, Greek -->
<!ENTITY Theta "&#x00398;">
<!--/Theta capital Theta, Greek -->
<!ENTITY thetav "&#x003D1;">
<!--/vartheta - curly or open theta -->
<!ENTITY upsi "&#x003C5;">
<!--/upsilon small upsilon, Greek -->
<!ENTITY Upsi "&#x003D2;">
<!--/Upsilon capital Upsilon, Greek -->
<!ENTITY xi "&#x003BE;">
<!--/xi small xi, Greek -->
<!ENTITY Xi "&#x0039E;">
<!--/Xi capital Xi, Greek -->
<!ENTITY zeta "&#x003B6;">
<!--/zeta small zeta, Greek -->
<!ENTITY Upsilon "&#x003D2;">
<!--alias ISOGRK3 Upsi -->
<!ENTITY upsilon "&#x003C5;">
<!--alias ISOGRK3 upsi -->

=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/xml/Geometrie/Kurven/Kubische Kurven/bspline_kurz.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE math4u2 PUBLIC "-//FH Augsburg//DTD Math4u2//DE" "http://www.math4u2.de/xml/dtd/math4u2DTD.dtd">
<math4u2>
	<head>
		<version>2.0</version>
		<author>Dr. M. Weiss</author>
		<module id="main" class="ShowMeGraph"/>
	</head>
	<body>
		<location>Geometrie/Kurven/Kubische Kurven</location>
		<title>kubische B-Splines - kurz</title>
		<summary>Experimente mit uniformen nichtrationalen kubischen B-Splines.</summary>
		<keywords>
			<keyword>Spline</keyword>
			<keyword>B-Spline</keyword>
			<keyword>uniform</keyword>
			<keyword>nichtrational</keyword>
			<keyword>Gewichtsfunktion</keyword>
			<keyword>Basisfunktion</keyword>
		</keywords>
		<step>
			<title>Uniforme nichtrationale kubische B-Splines</title>
			<description>
				<strong>links</strong>: Zeit über Doppelpfeil t verändern.
				<br/><strong>rechts</strong>: Steuerpunkte bewegen.</description>
			<layout>
				<row perc="100">
					<col perc="50" name="gewichte"/>
					<col perc="50" name="kurven"/>
				</row>
			</layout>
			<seq>
				<script>
		      deleteAll();
					kurven.coordinateSystem(xMin=0.5;xMax=10;yMin=1;yMax=8);	
					kurven.setTitle( title = "Kurve");
					gewichte.coordinateSystem(xMin=-1.51;xMax=2.51;yMin=-0.5;yMax=1.5);					
					gewichte.setTitle( title = "Gewichtsfunktionen");
										
					expand( left = false; right = false );
					newObject( def = t:=punkt( 0.2, fix(-0.35)); color = magenta;style =  ARROW_H; target = gewichte);
					newObject( def = tg := gerade( t, e2y); linestyle = dot; target = gewichte );
					newObject( def = p0:=punkt(1, 6); target = kurven; );
					newObject( def = p1:=punkt(4, 4.2); colr = red; target = kurven; );
					newObject( def = p2:=punkt(2, 2.2); color = blue; target = kurven; );
					newObject( def = p3:=punkt(6.37, 2.2); color = green; target = kurven; );
					newObject( def = p4:=punkt(7, 5.3); color = orange; target = kurven; );
					newObject( def = p5:=punkt(8.6, 4.5); color = gray; target = kurven; );
					newObject( def = pp:=&lt;punkt>liste0({p0, p1,p2,p3,p4,p5}); );
					newObject( def = g1(t):=1/6*(1-t)^3 );
					newObject( def = g2(t):=1/6*(3*t^3-6*t^2+4) );
					newObject( def = g3(t):=1/6*(-3*t^3+3*t^2+3*t+1));
					newObject( def = g4(t):=1/6*t^3 );					
					newObject( def =gg4(t) := t^3/6 );
					newObject( def = gg3(t) := (-t^3+t^2+t+1/3)/2);
					newObject( def = gg2(t) := (3*t^3-6*t^2+4)/6);
					newObject( def =gg1(t) := (1-t)^3/6 );


					newObject( def = polx(i,t) := pp[i-1].x*gg1(t)+pp[i].x*gg2(t)+pp[i+1].x*gg3(t)+pp[i+2].x*gg4(t) );
					newObject( def = poly(i,t) := pp[i-1].y*gg1(t)+pp[i].y*gg2(t)+pp[i+1].y*gg3(t)+pp[i+2].y*gg4(t) );
					newObject( def =py(t) := p1.y*g1( t)+p2.y*g2( t)+p3.y*g3( t)+p4.y*g4( t) );
					newObject( def = px(t) := p1.x*g1( t)+p2.x*g2( t)+p3.x*g3( t)+p4.x*g4( t));
										newObject( def = mark0:=marker(px(0), py(0) ); target = kurven );
					newObject( def = mark1:=marker(px(1), py(1) ); target = kurven );
					newObject( def =spline1:=kurve(t,0,1,polx(1,t),poly(1,t)); linestyle = dot;  target = kurven );
					newObject( def =spline2:=kurve(t,0,1,polx(2,t),poly(2,t)); target = kurven );
					newObject( def =spline3:=kurve(t,0,1,polx(3,t),poly(3,t)); linestyle = dash; target = kurven );
					

		      
					
					newObject( def = flaecheLinks:= flaeche({punkt(-1, 0), punkt(0,0), punkt(0, 10), punkt(-1, 10 )}); fillcolor = 100.100.100.100;  target = gewichte );
					newObject( def = flaecheRechts:= flaeche({punkt(1, 0), punkt(2,0), punkt(2, 10), punkt(1, 10 )}); fillcolor = 100.100.100.100; target = gewichte );
					newObject( def = streckeLinks := strecke( punkt(-1, -0.2), punkt(0,-0.2) ) ; linestyle = dot; target = gewichte );
					newObject( def = streckeMitte := strecke( punkt(0, -0.2), punkt(1,-0.2) ) ; target = gewichte );
					newObject( def = streckeRechts := strecke( punkt(1, -0.2), punkt(2,-0.2) ) ; linestyle = dash; target = gewichte );
					
					newObject( def = m10:= marker( -0.875, 1.1); color = black; target = gewichte );
					newObject( def = m11:= marker( -0.625, 1.1); color =red; target = gewichte );
					newObject( def = m12:= marker( -0.375, 1.1); color = blue; target = gewichte );
					newObject( def = m13:= marker( -0.125, 1.1); color = green; target = gewichte );
					
					
					newObject( def = m21:= marker( 0.125, 1.1); color =red; target = gewichte );
					newObject( def = m22:= marker( 0.375, 1.1); color = blue; target = gewichte );
					newObject( def = m23:= marker( 0.625, 1.1); color = green; target = gewichte );
					newObject( def = m24:= marker( 0.875, 1.1); color = orange; target = gewichte );
					
					newObject( def = m32:= marker( 1.125, 1.1); color = blue; target = gewichte );
					newObject( def = m33:= marker( 1.375, 1.1); color = green; target = gewichte );
					newObject( def = m34:= marker( 1.625, 1.1); color = orange; target = gewichte );
					newObject( def = m35:= marker( 1.875, 1.1); color =gray; target = gewichte );


					
					newObject( def = tt :=t.x );
		         newObject( def = kind := ceil(tt)+1 );
		         newObject( def = km := marker(polx(kind,tt+2-kind), poly(kind,tt+2-kind)); color = magenta; target = kurven );

		         newObject( def = g14:=kurve(t,-1,0,t ,0); color = orange;  target = gewichte );
		       newObject( def = g24:=kurve(t,0,1,t ,g4(t)); color = orange; target = gewichte );



                  		      newObject( def = g21:=kurve(t,0,1,t ,g1(t)); color = red; target = gewichte );

                            	newObject( def = g32:=kurve(t,1,2,t ,g1(t-1)); color = blue; linestyle = dash; target = gewichte );
		     				

		          newObject( def = g22:=kurve(t,0,1,t ,g2(t)); color = blue; target = gewichte );
		                            newObject( def = g12:=kurve(t,-1,0,t ,g3(t+1)); color = blue; linestyle = dot; target = gewichte );
		                            newObject( def = g23:=kurve(t,0,1,t ,g3(t)); color = green; target = gewichte );



		     
					
					
					
					newObject( def = g10:=kurve(t,-1,0,t ,g1(t+1)); linestyle = dot; target = gewichte );
					newObject( def = g11:=kurve(t,-1,0,t ,g2(t+1)); color = red; linestyle = dot; target = gewichte );

					newObject( def = g13:=kurve(t,-1,0,t ,g4(t+1)); color = green; linestyle = dot; target = gewichte );

					newObject( def = g33:=kurve(t,1,2,t ,g2(t-1)); color = green; linestyle = dash; target = gewichte );
					newObject( def = g34:=kurve(t,1,2,t ,g3(t-1)); color = orange; linestyle = dash; target = gewichte );
					newObject( def = g35:=kurve(t,1,2,t ,g4(t-1)); color = gray; linestyle = dash; target = gewichte );
					
					

		      </script>
			</seq>
		</step>
	</body>
</math4u2>

=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/doc/hilfe/02Bedienung/02.00Bedienung.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE math4u2 PUBLIC "-//FH Augsburg//DTD Math4u2//DE" "http://www.math4u2.de/xml/dtd/math4u2DTD.dtd">
<math4u2>
	<head>
		<version>2.0</version>
		<author>Stefan Fenn, Erich Seifert, Prof. Dr. Maximilian Weiﬂ</author>
		<module id="main" class="ShowMeGraph"/>
	</head>
	<body>
		<location>2. Bedienung</location>
		<title>2.0 Bedienung</title>
		<step>
			<title>2 Bedienung</title>
			<description>
Hier finden sie Details zur Bedienung von math4u2.
<br/>Einen kurzen Einblick in die wichtigsten Bedienkonzepte 
gibt der Abschnitt 1.2 des Kapitels 1.
			</description>
		</step>
	</body>
</math4u2>

=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/doc/hilfe/02Bedienung/02.03Objekte-inspizieren-und-veraendern.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE math4u2 PUBLIC "-//FH Augsburg//DTD Math4u2//DE" "http://www.math4u2.de/xml/dtd/math4u2DTD.dtd">
<math4u2>
	<head>
		<version>2.0</version>
		<author>Stefan Fenn, Erich Seifert, Prof. Dr. Maximilian Weiß</author>
		<module id="main" class="ShowMeGraph"/>
	</head>
	<body>
		<location>2. Bedienung</location>
		<title>2.3 Objekte inspizieren und verändern</title>
		<step>
			<title>2.3 Objekte inspizieren und verändern:<p/>Detailsicht und Detailliste</title>
			<description>			
				
Für viele Objekte kann eine Detailsicht erzeugt werden. Eine Detailscht dient 
dazu, einzelne Eigenschaften eines Objekts zu beobachten oder zu verändern.

<p/>Die Form einer Detailsicht hängt vom Typ des zugehörigen Objekts ab. 
Mehr Informationen dazu finden Sie deshalb bei der Beschreibung der 
verschiedenen Objekt-Typen.

<p/>In der Detailliste können mehrere Detailsichten verwaltet werden. 
In der Regel wird man nur von den wenigen Objekten eine Detailsicht 
erzeugen, die aktuell von besonderem Interesse sind. Die nicht mehr 
benötigten Detailsichten können gelöscht weden, ohne dass davon das 
eigentliche Objekt betroffen ist.	

<p/><strong>Detailsicht erzeugen</strong>
<p/>Sie erzeugen eine Detailsicht eines Objekts, indem Sie das 
entsprechende Element der Definitionsliste mit gedrückter Maustaste 
nach rechts auf den Verankerungsplatz der Detailliste ziehen.			
				
<p/><img src="math4u2/doc/images/bedienung/detailsicht-erzeugen01.gif"/>

<p/><strong>Maus-Detailsicht</strong>
<br/>Zum Verfolgen der aktuellen Maus-Koordinaten können Sie eine Detailsicht 
erzeugen, indem Sie im Menü der Steuerleiste (siehe 2.1.1) das Element 
"Mauskoordinaten anzeigen" auswählen.

<p/><strong>Detailsicht löschen</strong>
<br/>Sie löschen die Detailsicht eines Objekts,
<br/>
<ul>
	<li>indem Sie diese mit der Maus markieren und dann die ENTF-Taste drücken oder</li>
	<li>indem Sie die Sicht mit gedrücketer Maustaste in den math4u2-Papierkorb ziehen.</li>
</ul>
<p/><strong>Achtung:</strong>
<br/>Beim Löschen einer Detailsicht bleibt das eigentliche Objekt erhalten.

			</description>
		</step>
	</body>
</math4u2>

=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/xml/Geometrie/Kurven/Kubische Kurven/hermite_kurz.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE math4u2 PUBLIC "-//FH Augsburg//DTD Math4u2//DE" "http://www.math4u2.de/xml/dtd/math4u2DTD.dtd">
<math4u2>
	<head>
		<version>2.0</version>
		<author>Dr. Weiss</author>
		<module id="main" class="ShowMeGraph"/>
	</head>
	<body>
		<location>Geometrie/Kurven/Kubische Kurven</location>
		<title>Hermite-Kurven - kurz</title>
		<step>
			<title>Hermite-Kurven - kurz</title>
			<description>
				<strong>links</strong>: Zeit über Doppelpfeil t verändern.
				<br/><strong>rechts</strong>: Steuerpunkte bewegen, Geschwindigkeitsvektoren (Richtung, Länge) verändern.</description>

						<layout>
				<row perc="100">
					<col perc="40" name="gewichte"/>
					<col perc="60" name="kurve"/>
				</row>
			</layout>
			<seq>
				<script>
			      deleteAll();
				  gewichte.coordinateSystem(xMin=-0.2; xMax=1.3; yMin=-0.2; yMax=1.2);
				  kurve.coordinateSystem(xMin=0.2;xMax=3.5;yMin=0.2; yMax=2.4);
				  
			      expand( left = false; right = false );
			      gewichte.setTitle( title="Gewichtsfunktionen" );
			      kurve.setTitle( title="Geometrische Größen, Kurve" );

                  newObject( def = gg1 := gerade( punkt( 1, 0 ) , vektor({0,1} ) ) ; target = gewichte );
			      newObject( def =  p1:=punkt(1.3,0.6); color = red; target = kurve);
			      newObject( def =  p2:=punkt(2.3,1.9); color = green; target = kurve);
			      newObject( def = v1:= vektor({ -0.7, 1.2 } ) );
			      newObject( def = pf1 := pfeil( p1, v1 ) ; color = blue; target = kurve );
			       newObject( def = v2:= vektor({ 0.3, -0.7 } ) );
			      newObject( def = pf2 := pfeil( p2, v2 ) ; color = magenta; target = kurve );  
			      newObject( def = recl:= flaeche({ punkt(-1,-1), punkt(0,-1), punkt( 0, 2), punkt(-1,2)}); fillcolor = 255.255.255.220; target = gewichte);
			      newObject( def = recr:= flaeche({ punkt(1,-1), punkt(2,-1), punkt( 2, 2), punkt(1,2)}); fillcolor = 255.255.255.220; target = gewichte);
			       newObject( def =  f1(t):=2*t^3-3*t^2+1;   );
			       newObject( def =  f2(t):=-2*t^3+3*t^2 );
			       newObject( def =   f3(t):=t^3-2*t^2+t);
			       newObject( def =  f4(t):=t^3-t^2 );
			       newObject( def =  sx(t):=p1.x*f1(t)+p2.x*f2(t)+v1.x*f3(t)+v2.x*f4(t) );
			       newObject( def =  sy(t):=p1.y*f1(t)+p2.y*f2(t)+v1.y*f3(t)+v2.y*f4(t) );
			       newObject( def = s:=kurve(t,0,1,sx(t),sy(t))  );
			    			      newObject( def = f1g:=kurve(t,0,1,t,f1(t)); color = red; target = gewichte );
			    			       newObject( def = f2g:=kurve(t,0,1,t,f2(t)); color = green; target = gewichte);
			    			        newObject( def =f3g:=kurve(t,0,1,t,f3(t)) ; color = blue; target = gewichte);
			    			        			      newObject( def = f4g:=kurve(t,0,1,t,f4(t)); color = magenta; target = gewichte );
			      			       newObject( def = t:=punkt(0.2,fix(0.5)); color = gray; style =  ARROW_H; target = gewichte );
			     			       newObject( def = t0:=max(0,min(t.x,1)) );
			       newObject( def = g:=gerade(punkt(t0,0),e2y) ; color =darkGray ; target = gewichte; linestyle = dot);
			       newObject( def =pt:=punkt(fix(sx(t0)),fix(sy(t0))) ; style = CIRCLE_DOT; target = kurve );
				   			       modifyObject( name = s; color = gray; target = kurve );
			    </script>
			</seq>
		</step>
	</body>
</math4u2>

=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/xml/Geometrie/Kurven/trochoiden.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE math4u2 PUBLIC "-//FH Augsburg//DTD Math4u2//DE" "http://www.math4u2.de/xml/dtd/math4u2DTD.dtd">
<math4u2>
	<head>
		<version>2.0</version>
		<author>unknown</author>
		<module id="main" class="ShowMeGraph"/>
	</head>
	<body>
		<location>Geometrie/Kurven</location>
		<title>Trochoiden</title>
		<step>
			<title>Trochoiden</title>
			<description>Text<br/>
</description>

			<seq>
				<call object="main" action="deleteAll"/>
				<call object="main" action="expandLists">
					<param type="boolean" value="false"/>
				</call>
				<script>
				
              
			  newObject( def= da.xMin :=-5 );
			  newObject( def= da.xMax := 5 );
			  newObject( def= da.yMin := -2.6 );
			  newObject( def= da.yMax := 2.6 );


			  newObject( def= O:=punkt(1,1); target=da);
			  newObject(def=R:=2);
			  newObject(def=F:=kreis(O,R); target = da);
			  newObject(def=phi:=0);
			  newObject(def=r:=1);
			  newObject(def=rdiff:=vektor({(R+r)*cos(phi), (R+r)*sin(phi)}));
			  newObject(def=rM:=O.r+rdiff);
			  newObject(def=M:=punkt(rM.x,rM.y); target = da );
			  newObject(def=K:=kreis(M,r); target = da );
			  newObject(def=a:=0.7);
			  newObject(def=rPx(t):=(R+r)*cos(t)-a*cos((R+r)/r*t) );
			  newObject(def=rPy(t):=(R+r)*sin(t)-a*sin((R+r)/r*t) );
			  newObject(def=rPr:=vektor({rPx(phi),rPy(phi) }));
			  newObject(def=rP:=O.r+rPr);
			  newObject(def=P:=punkt(rP.x,rP.y); target = da );
			  newObject(def=trochoide:=kurve(t,0,phi,O.x + rPx(t),O.y + rPy(t)); color = green; target = da);
			  			</script>
			  				
			</seq>
		</step>
		<step>
		<title>Animation</title>
		<seq>
		<animate object="main" parameterName="phi" to="20" end="40"/>
		</seq>
		</step>
		<step>
		<title>Anderes Verhältnis</title>
		<seq>
		  <script>
		     newObject( def=phi:=0; );
		     newObject( def=R:=2.1;);
		  </script>
		  <animate object="main" parameterName="phi" to="20" end="40"/>
		</seq>
		</step>
	</body>
</math4u2>

=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/doc/hilfe/03Objekte/03.05.02Punktfolge.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE math4u2 PUBLIC "-//FH Augsburg//DTD Math4u2//DE" "http://www.math4u2.de/xml/dtd/math4u2DTD.dtd">
<math4u2>
	<head>
		<version>2.0</version>
		<author>Stefan Fenn, Erich Seifert, Prof. Dr. Maximilian Weiß</author>
		<module id="main" class="ShowMeGraph"/>
	</head>
	<body>
		<location>3. Daten, Funktionen, Objekte, Graphen/3.5 Diagramme und Textelemente</location>
		<title>3.5.2 Folge von Punkten</title>
		<step>
			<title>3.5.2 Folge von Punkten</title>
			<description>
<strong>Folge von Punkten definieren</strong>
Eine Punktfolge <code>pf:=punktFolge( xf, yf, s, r, layout )</code> stellt für zwei Zahlenfolgen <code>xf</code>
und <code>yf</code> die Punkte <f>punkt(xf[1],yf[1])</f>, <f>punkt(xf[2],yf[2])</f>, <f>punkt(xf[3],yf[3])</f>, ... dar.
<br/>Der Term <code>s</code> gibt an, bis zu welchem Folgenglied die Darstellung erfolgen soll.
<br/>Der Term <code>r</code> bestimmt den Radius der Markierungen.
<br/>Die Konstante <code>layout</code> legt die Art der Darstellung fest. Möglich sind folgende Werte:
<br/><strong>P</strong>: Es werden nur die Punkte gezeichnet.
<br/><strong>S</strong>: Die Punkte werden durch einen Streckenzug verbunden, dieser wird gezeichnet.
<br/><strong>PS</strong> oder <strong>SP</strong>: Die Punkte und der zugehörige Streckenzug werden gezeichnet.
				
<p/><strong>Beispiel</strong>
<br/>Die Folgenglieder der geometrischen Reihe zu
<code>q:=0.5</code> solle graphisch dargestellt werden.
Die Folgenglieder selbst definiert man als
<br/><code>geom:=folge0(i,{1},geom[i-1]+q^i)</code>
<br/>Als x-Koordinaten für die Darstellung der Folge definiert man eine weitere Folge
<br/><code>xk:=folge0(i,{},i)</code>
<br/><code>t:=20</code> wird verwendet, um festzulegen, wie viele Glieder dargestellt werden.
Jetzt stellt <code>geopunkte:=punktFolge(xk, geom, t, 1, P)</code> die ersten 21 Elemente der
Folge graphisch dar.
			</description>
		</step>
	</body>
</math4u2>
