=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/xml/dtd/math4u2DTD.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--Hauptelement. Es dient als Wurzel für alle weiteren Knotenelemente.-->
<!ELEMENT math4u2 (head?, body)>
<!--Körper des Dokuments für den eigentlichen Inhalt-->
<!ELEMENT body (location?, title, summary?, keywords?, step+, exercise*)>
<!--Eine einfache Ja-/Nein-Frage-->
<!ELEMENT choice (statement, solution, explanation?)>
<!--Setzen des Layouts-->
<!ELEMENT layout (row+)+>
<!--Gruppe von parallel ausführbaren Plugin-Aktionen-->
<!ELEMENT par (animate | call | par | seq | script)*>
<!--Eine Multiple-Choice-Frage-->
<!ELEMENT selection (description?, choice)+>
<!ATTLIST selection
	mutual CDATA #IMPLIED
>
<!--Gruppe von sequentiell ausführbaren Plugin-Aktionen-->
<!ELEMENT seq (animate | call | par | seq | script)*>
<!ATTLIST seq
	repeat CDATA #IMPLIED
>
<!ELEMENT script ANY>
<!ELEMENT location (#PCDATA)>
<!--Datentyp für formattierbaren (gemischten) Text mit Formeln, Auszeichnungen und Bildern-->
<!ELEMENT title (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Zusammenfassung des Themas-->
<!ELEMENT summary (#PCDATA)>

<!ELEMENT keywords (keyword)*>

<!ELEMENT keyword (#PCDATA)>

<!ELEMENT step (title?, description?, layout?, (par | seq)*)>
<!--Übungen-->
<!ELEMENT exercise (title?, description?, summary?, (seq | par)*, (choice | selection)+)>
<!--Aussage-->
<!ELEMENT statement (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Lösung-->
<!ELEMENT solution (#PCDATA)>
<!--Begründung-->
<!ELEMENT explanation (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Reihe des Layouts-->
<!ELEMENT row (col+)+>
<!ATTLIST row
	perc CDATA #REQUIRED
>
<!--Kopf des Dokuments für nicht sichtbare Definitionen-->
<!ELEMENT head (version, author?, meta*, module*)>
<!--Animation eines bestimmten Attributs eines Moduls-->
<!ELEMENT animate EMPTY>
<!ATTLIST animate
	object CDATA #REQUIRED
	getAction CDATA #IMPLIED
	setAction CDATA #IMPLIED
	parameterName CDATA #REQUIRED
	from CDATA #IMPLIED
	to CDATA #REQUIRED
	by CDATA #IMPLIED
	begin CDATA #IMPLIED
	end CDATA #REQUIRED
	dur CDATA #IMPLIED
	timeFunction CDATA #IMPLIED
>
<!--Aktionsaufruf an ein Modul-->
<!ELEMENT call (param*)>
<!ATTLIST call
	object CDATA #REQUIRED
	action CDATA #REQUIRED
	begin CDATA #IMPLIED
	end CDATA #IMPLIED
	dur CDATA #IMPLIED
>
<!--Stellen einer Frage-->
<!ELEMENT description (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Mathematische Formel: Es ist MathML realisiert, sowie eine Math4u2-Schreibweise. Bei letzeren wird kein Attribut "type" angegeben. Bei "show=" können nun 3 verschiedene Darstellungsarten festgelegt werden. 1.formal z.B. f(x):=a*x. 2. actual z.B. f(x):=2*x (Parameter wird eingesetzt und kann verändert werden). 3. short z.B. f(x)-->
<!ELEMENT formula (#PCDATA | conf)*>
<!ATTLIST formula
	type CDATA #IMPLIED
	show CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
>
<!--Kurzform von formula-->
<!ELEMENT f (#PCDATA | conf)*>
<!ATTLIST f
	bgcolor CDATA #IMPLIED
>
<!--Kurzform von formula show = "short"-->
<!ELEMENT fh (#PCDATA | conf)*>
<!ATTLIST fh
	bgcolor CDATA #IMPLIED
>
<!--Kurzform von formula show="body"-->
<!ELEMENT fb (#PCDATA | conf)*>
<!ATTLIST fb
	bgcolor CDATA #IMPLIED
>
<!--Formeldefinition-->
<!ELEMENT fd (#PCDATA)>
<!ATTLIST fd
	bgcolor CDATA #IMPLIED
	width CDATA #IMPLIED
>
<!ELEMENT conf (#PCDATA)>
<!--Referenz auf andere Abschnitte-->
<!ELEMENT ref (#PCDATA)>
<!ATTLIST ref
	target IDREF #IMPLIED
>
<!--Absatz-->
<!ELEMENT p (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Zeilenumbruch-->
<!ELEMENT br ANY>
<!--Normal betonter Text-->
<!ELEMENT em (#PCDATA)>
<!--Stark betonter Text-->
<!ELEMENT strong (#PCDATA)>
<!--Verweis auf ein Bild-->
<!ELEMENT img EMPTY>
<!ATTLIST img
	src CDATA #REQUIRED
>
<!--Code Text-->
<!ELEMENT code (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Tablulator-->
<!ELEMENT tab ANY>
<!--Kommando bzw. Funktionalität-->
<!ELEMENT command (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Tabelle angelehnt an HTML-->
<!ELEMENT table (tr)+>
<!ATTLIST table
	border CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
>
<!--Unorderd List angelehnt an HTML-->
<!ELEMENT ul (li)+>
<!ELEMENT col EMPTY>
<!ATTLIST col
	perc CDATA #REQUIRED
	name CDATA #REQUIRED
	type CDATA #IMPLIED
>
<!--Versionsnummer des Dokuments-->
<!ELEMENT version (#PCDATA)>
<!--Autor(en) des  des Dokuments-->
<!ELEMENT author (#PCDATA)>
<!--Zusätzliche Meta-Information-->
<!ELEMENT meta EMPTY>
<!ATTLIST meta
	name CDATA #REQUIRED
	content CDATA #REQUIRED
>
<!--Zum Anmelden eines externes Moduls (z. B. von Graphendarstellung, Soundeinbindung oder von selbstgeschriebenen Modulen). Die Module werden in der Datei math4u2/conf/config.properties näher bestimmt. Jedes Modul muß in Java von JPanel abgeleitet sein.-->
<!ELEMENT module EMPTY>
<!ATTLIST module
	class CDATA #REQUIRED
	id ID #REQUIRED
>
<!--Einzelner Parameter für den Aktionsaufruf-->
<!ELEMENT param EMPTY>
<!ATTLIST param
	type CDATA #REQUIRED
	value CDATA #REQUIRED
>
<!ELEMENT tr (td)+>
<!--list item-->
<!ELEMENT li (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!--Datentyp für formattierbaren (gemischten) Text mit Formeln, Auszeichnungen und Bildern-->
<!ELEMENT td (#PCDATA | formula | f | fd | fh | fb | ref | p | br | em | strong | img | code | tab | command | table | ul)*>
<!ATTLIST td
	bgcolor CDATA #IMPLIED
>
<!-- Entities -->
<!ENTITY not "&#x000AC;">
<!--/neg /lnot =not sign -->
<!ENTITY ne "&#x02260;">
<!--/ne /neq R: not equal -->
<!ENTITY equals "&#x0003D;">
<!--=equals sign R: -->
<!ENTITY NotEqual "&#x02260;">
<!--alias ISOTECH ne -->
<!ENTITY equiv "&#x02261;">
<!--/equiv R: identical with -->
<!ENTITY le "&#x02264;">
<!-- less equal -->
<!ENTITY ge "&#x02265;">
<!--/geq /ge R: greater-than-or-equal -->
<!ENTITY sub "&#x02282;">
<!--/subset R: subset or is implied by -->
<!ENTITY sup "&#x02283;">
<!--/supset R: superset or implies -->
<!ENTITY nsub "&#x02284;">
<!--not subset -->
<!ENTITY sube "&#x02286;">
<!--/subseteq R: subset, equals -->
<!ENTITY supe "&#x02287;">
<!--/supseteq R: superset, equals -->
<!ENTITY oplus "&#x02295;">
<!--/oplus B: plus sign in circle -->
<!ENTITY otimes "&#x02297;">
<!--/otimes B: multiply sign in circle -->
<!ENTITY perp "&#x022A5;">
<!--/perp R: perpendicular -->
<!ENTITY forall "&#x02200;">
<!--/forall for all -->
<!ENTITY part "&#x02202;">
<!--/partial partial differential -->
<!ENTITY exist "&#x02203;">
<!--/exists at least one exists -->
<!ENTITY nabla "&#x02207;">
<!--/nabla del, Hamilton operator -->
<!ENTITY isin "&#x02208;">
<!--/in R: set membership  -->
<!ENTITY Element "&#x02208;">
<!--/in R: set membership  -->
<!ENTITY notin "&#x02209;">
<!--/notin N: negated set membership -->
<!ENTITY ni "&#x0220B;">
<!--/ni /owns R: contains -->
<!ENTITY prop "&#x0221D;">
<!--/propto R: is proportional to -->
<!ENTITY infin "&#x0221E;">
<!--/infty infinity -->
<!ENTITY ang "&#x02220;">
<!--/angle - angle -->
<!ENTITY and "&#x02227;">
<!--/wedge /land B: logical and -->
<!ENTITY or "&#x02228;">
<!--/vee /lor B: logical or -->
<!ENTITY cap "&#x02229;">
<!--/cap B: intersection -->
<!ENTITY cup "&#x0222A;">
<!--/cup B: union or logical sum -->
<!ENTITY sim "&#x0223C;">
<!--/sim R: similar -->
<!ENTITY cong "&#x02245;">
<!--/cong R: congruent with -->
<!ENTITY asymp "&#x0224D;">
<!--/asymp R: asymptotically equal to -->
<!ENTITY minus "&#x02212;">
<!--B: minus sign -->
<!ENTITY plus "&#x0002B;">
<!--=plus sign B: -->
<!ENTITY plusmn "&#x000B1;">
<!--/pm B: =plus-or-minus sign -->
<!-- Pfeille -->
<!ENTITY larr "&#x02190;">
<!--/leftarrow /gets A: =leftward arrow -->
<!ENTITY rarr "&#x02192;">
<!--/rightarrow /to A: =rightward arrow -->
<!ENTITY uarr "&#x02191;">
<!--/uparrow A: =upward arrow -->
<!ENTITY darr "&#x02193;">
<!--/downarrow A: =downward arrow -->
<!ENTITY harr "&#x02194;">
<!--/leftrightarrow A: l&r arrow -->
<!ENTITY lArr "&#x021D0;">
<!--/Leftarrow A: is implied by -->
<!ENTITY rArr "&#x021D2;">
<!--/Rightarrow A: implies -->
<!ENTITY uArr "&#x021D1;">
<!--/Uparrow A: up dbl arrow -->
<!ENTITY dArr "&#x021D3;">
<!--/Downarrow A: down dbl arrow -->
<!ENTITY hArr "&#x021D4;">
<!--/Leftrightarrow A: l&r dbl arrow -->
<!-- Griechische Zeichen -->
<!ENTITY fnof "&#x00192;">
<!--function of (italic small f) -->
<!ENTITY alpha "&#x003B1;">
<!--/alpha small alpha, Greek -->
<!ENTITY beta "&#x003B2;">
<!--/beta small beta, Greek -->
<!ENTITY chi "&#x003C7;">
<!--/chi small chi, Greek -->
<!ENTITY delta "&#x003B4;">
<!--/delta small delta, Greek -->
<!ENTITY Delta "&#x00394;">
<!--/Delta capital Delta, Greek -->
<!ENTITY epsi "&#x003B5;">
<!--/straightepsilon, small epsilon, Greek -->
<!ENTITY epsiv "&#x0025B;">
<!--/varepsilon -->
<!ENTITY eta "&#x003B7;">
<!--/eta small eta, Greek -->
<!ENTITY gamma "&#x003B3;">
<!--/gamma small gamma, Greek -->
<!ENTITY Gamma "&#x00393;">
<!--/Gamma capital Gamma, Greek -->
<!ENTITY gammad "&#x003DC;">
<!--/digamma -->
<!ENTITY Gammad "&#x003DC;">
<!--capital digamma -->
<!ENTITY iota "&#x003B9;">
<!--/iota small iota, Greek -->
<!ENTITY kappa "&#x003BA;">
<!--/kappa small kappa, Greek -->
<!ENTITY kappav "&#x003F0;">
<!--/varkappa -->
<!ENTITY lambda "&#x003BB;">
<!--/lambda small lambda, Greek -->
<!ENTITY Lambda "&#x0039B;">
<!--/Lambda capital Lambda, Greek -->
<!ENTITY mu "&#x003BC;">
<!--/mu small mu, Greek -->
<!ENTITY nu "&#x003BD;">
<!--/nu small nu, Greek -->
<!ENTITY omega "&#x003C9;">
<!--/omega small omega, Greek -->
<!ENTITY Omega "&#x003A9;">
<!--/Omega capital Omega, Greek -->
<!ENTITY phi "&#x003C6;">
<!--/straightphi - small phi, Greek -->
<!ENTITY Phi "&#x003A6;">
<!--/Phi capital Phi, Greek -->
<!ENTITY phiv "&#x003D5;">
<!--/varphi - curly or open phi -->
<!ENTITY pi "&#x003C0;">
<!--/pi small pi, Greek -->
<!ENTITY Pi "&#x003A0;">
<!--/Pi capital Pi, Greek -->
<!ENTITY piv "&#x003D6;">
<!--/varpi -->
<!ENTITY psi "&#x003C8;">
<!--/psi small psi, Greek -->
<!ENTITY Psi "&#x003A8;">
<!--/Psi capital Psi, Greek -->
<!ENTITY rho "&#x003C1;">
<!--/rho small rho, Greek -->
<!ENTITY rhov "&#x003F1;">
<!--/varrho -->
<!ENTITY sigma "&#x003C3;">
<!--/sigma small sigma, Greek -->
<!ENTITY Sigma "&#x003A3;">
<!--/Sigma capital Sigma, Greek -->
<!ENTITY sigmav "&#x003C2;">
<!--/varsigma -->
<!ENTITY tau "&#x003C4;">
<!--/tau small tau, Greek -->
<!ENTITY theta "&#x003B8;">
<!--/theta straight theta, small theta, Greek -->
<!ENTITY Theta "&#x00398;">
<!--/Theta capital Theta, Greek -->
<!ENTITY thetav "&#x003D1;">
<!--/vartheta - curly or open theta -->
<!ENTITY upsi "&#x003C5;">
<!--/upsilon small upsilon, Greek -->
<!ENTITY Upsi "&#x003D2;">
<!--/Upsilon capital Upsilon, Greek -->
<!ENTITY xi "&#x003BE;">
<!--/xi small xi, Greek -->
<!ENTITY Xi "&#x0039E;">
<!--/Xi capital Xi, Greek -->
<!ENTITY zeta "&#x003B6;">
<!--/zeta small zeta, Greek -->
<!ENTITY Upsilon "&#x003D2;">
<!--alias ISOGRK3 Upsi -->
<!ENTITY upsilon "&#x003C5;">
<!--alias ISOGRK3 upsi -->

=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/doc/hilfe/03Objekte/03.03.06Partielle-Ableitung.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE math4u2 PUBLIC "-//FH Augsburg//DTD Math4u2//DE" "http://www.math4u2.de/xml/dtd/math4u2DTD.dtd">
<math4u2>
	<head>
		<version>2.0</version>
		<author>Stefan Fenn, Erich Seifert, Prof. Dr. Maximilian Weiß</author>
		<module id="main" class="ShowMeGraph"/>
	</head>
	<body>
		<location>3. Daten, Funktionen, Objekte, Graphen/3.3 Funktionen</location>
		<title>3.3.6 Partielle Ableitung</title>
		<step>
			<title>3.3.6 Partielle Ableitung</title>
			<description>			
Mehrstellige Funktionen können partiell abgeleitet werden.
<br/>Mit <code>d(x,y):=pderive(x*y*sin(y), x, y, y)</code> wird <code>d(x,y)</code> als partielle 
Ableitung dritter Ordnung der Funktion <code>x*y*sin(y)</code> definiert, dabei wird zuerst nach 
der Variablen <code>x</code> differenziert, anschließend zweimal nach der Variablen <code>y</code>.
<p/>Wenn eine partielle Ableitung im Rahmen der Definition einer weiteren Funktion verwendet werden
soll, so geschieht dies wie bei
<br/><code>g(z):=z+pderive(vars(x,y), y*sin(x*y), y, y, x)(z, 2)</code>.
<p/>
Die einzelnen Bestandteile bedeuten:
<ul>
	<li>
Mit <code>vars(x, y)</code> bedeutet, dass <code>x</code> die erste Variable und <code>y</code>
die zweite Variable ist. Der Ableitung liegen diese beiden Variablen zugrunde.
	</li>
	<li>
Der Term <code>y*sin(x*y)</code> ist der Funktionsterm der abzuleitenden Funktion.
	</li>
	<li>
Differenziert wird zuerst zweimal nach <code>y</code>, dann einmal nach <code>x</code>.
	</li>
	<li>
In der entstehenden Funktion wie die (erste) Variable <code>x</code> durch die Variable der 
Funktion <code>g(z)</code> substituiert, die (zweite) Variable <code>y</code> durch die 
Zahl <code>2</code>.		
	</li>
</ul>
			</description>
		</step>
	</body>
</math4u2>

=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/doc/hilfe/03Objekte/03.03.04Summen-und-Produktiteratoren.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE math4u2 PUBLIC "-//FH Augsburg//DTD Math4u2//DE" "http://www.math4u2.de/xml/dtd/math4u2DTD.dtd">
<math4u2>
	<head>
		<version>2.0</version>
		<author>Stefan Fenn, Erich Seifert, Prof. Dr. Maximilian Weiß</author>
		<module id="main" class="ShowMeGraph"/>
	</head>
	<body>
		<location>3. Daten, Funktionen, Objekte, Graphen/3.3 Funktionen</location>
		<title>3.3.4 Summen- und Produktiterator</title>
		<step>
			<title>3.3.4 Summen- und Produktiterator</title>
			<description>			
<table>
	<tr>
		<td bgcolor="#F4C86C"><strong>Struktur</strong></td>
		<td bgcolor="#F4C86C"><strong>Bedeutung</strong></td>
	</tr>
	<tr>
		<td>
<code>sum(index,unten,oben,term)</code>
<br/><br/>
wie z.B.
<br/><br/>
<code>f(x):=sum(i,0,3,x^i)</code>
		</td>
		<td>
Summe
<br/><code>index</code>: Bezeichner für den Summationsindex
<br/><code>unten</code>: Term für die untere Summationsgrenze
<br/>mit ganzzahligem Wert
<br/><code>oben</code>: Term für die obere Summatioonsgrenze
<br/>mit ganzzahligem Wert
<br/><code>term</code>: Term für den Summanden			
		</td>
	</tr>	
	<tr>
		<td>
<code>prod(index,unten,oben,term)</code>
<br/><br/>
wie z.B.
<br/><br/>
<code>fak(i):=prod(ind,1,i,i)</code>
		</td>
		<td>
Produkt
<br/><code>index</code>: Bezeichner für den Summationsindex
<br/><code>unten</code>: Term für die untere Summationsgrenze
<br/>mit ganzzahligem Wert
<br/><code>oben</code>: Term für die obere Summatioonsgrenze
<br/>mit ganzzahligem Wert
<br/><code>term</code>: Term für den Faktor			
		</td>
	</tr>	
</table>

<p/>Zum Zeitpunkt der Auswertung müssen die Terme für die obere und 
die untere Summationsgrenze eine ganze Zahl als Wert liefern. Falls die 
Summationsgrenze über einen Parameter <code>a</code> verändert werden 
soll, kann man die Ganzzahligkeit z.B. durch <code>floor(a)</code> oder 
<code>ceil(a)</code> sicherstellen.
<p/>Wenn der Wert der oberen Grenze kleiner ist als der Wert der unteren 
Grenze, liefert <code>sum</code> das Ergebnis 0, <code>prod</code> das Ergebnis 1.

<p/><strong>Beispiel</strong>
<br/>Definiert man zunächst <code>n:=3</code>, so kann man mit
<code>tayCos(x):=sum(i,0,n,(-1)^i*x^(2*i)/(2*i)! )</code> das allgemeine Taylor-Polynom für
die cos-Funktion mit Entwicklungspunkt <f>c=0</f> definieren. Über den Wert 
von <code>n</code> kann man dann die Ordnung des Polynoms verändern.
			</description>
		</step>
	</body>
</math4u2>

=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/xml/Vorlagen/fenster1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE math4u2 PUBLIC "-//FH Augsburg//DTD Math4u2//DE" "http://www.math4u2.de/xml/dtd/math4u2DTD.dtd">
<math4u2>
	<head>
		<version>2.0</version>
		<author>unknown</author>
		<module id="main" class="ShowMeGraph"/>
	</head>
	<body>
		<location>Vorlagen/Zeichenflächen</location>
		<title>1. Eine Zeichenfläche</title>
		<summary>Vorlage für eine Zeichenfläche</summary>
		<step>
			<seq>
				<script>
				</script>
			</seq>
		</step>
	</body>
</math4u2>

=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/xml/Numerik/Integration/zusammeng_Newton_Cotes_Formeln.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Max Weiß (Fachhochschule Augsburg) -->
<!DOCTYPE math4u2 PUBLIC "-//FH Augsburg//DTD Math4u2//DE" "dtd/math4u2DTD.dtd">
<math4u2>
	<head>
		<version>2.1</version>
		<author>Dr. Weiss</author>
		<module id="main" class="ShowMeGraph"/>
	</head>
	<body>
		<location>Numerik/Integration</location>
		<title>Zusammengesetzte Newton-Cotes-Formeln</title>
		<summary>Zusammengesetzte Newton-Cotes-Formeln</summary>
		<step>
			<description>Wir ersetzen den Integranden durch das Interpolationspolynom vom Grad <f>2</f>: <f>f(x)=p[2](x)</f>,
		   <br/>dann wird aus dem Integral <f>int(x,a,b,f(x))=int(x,a,b,p[2](x))</f>
			</description>
		</step>
		<step>
			<description>Das Interpolationspolynom <f>p[2](x)</f> bestimmen wir mit dem Ansatz von Lagrange:
		   <br/>
				<f>p[2](x)=f(x[0])*l[0](x)+f(x[1])*l[1](x)+f(x[2])*l[2](x)</f>
			</description>
		</step>
		<step>
			<description>Wir schreiben das entstehende Integral
		   <br/>
				<f>int(x,a,b,p[2](x))=int(x,a,b,(f(x[0])*l[0](x)+f(x[1])*l[1](x)+f(x[2])*l[2](x)))</f> als Summe von Integralen
		   <br/>
				<f>int(x,a,b,f(x[0])*l[0](x))+int(x,a,b,f(x[1])*l[1](x))+int(x,a,b,f(x[2])*l[2](x))</f> und ziehen die Zahlenfaktoren .. vor das Integral
		   <br/>
				<f>f(x[0])*int(x,a,b,l[0](x))+f(x[1])*int(x,a,b,l[1](x))+f(x[2])*int(x,a,b,l[2](x))</f>
			</description>
		</step>
		<step>
			<description>Übrig bleiben die Integrale über die Lagrangefaktoren <f>l[0](x), l[1](x)</f> und <f>l[2](x)</f>.
		   <br/>Wichtig ist: Diese Integrale hängen nicht mehr von der zu integrierenden Funktion <f>f(x)</f> ab, sondern nur noch vom Integrationsintervall, letztlich nur noch von dessen Breite <f>h</f>. Wir können Sie also ohne Kenntnis von <f>f(x)</f> berechnen.
		   </description>
		</step>
		<step>
			<title>Aufgabe</title>
			<description>
				<f>int(x,a,b,p[2](x))=int(x,a,b,(f(x[0])*l[0](x)+f(x[1])*l[1](x)+f(x[2])*l[2](x)))=f(x[0])*int(x,a,b,l[0](x))+f(x[1])*int(x,a,b,l[1](x))+f(x[2])*int(x,a,b,l[2](x))</f>
				<br/>
				<f>int(x,a,b,l[0](x))=int(x,a,b,((x-x[1])*(x-x[2]))/((x[0]-x[1])*(x[0]-x[2])))=int(x,a,a+h,((x-(a+h/2))*(x-(a+h)))/((-h/2)*(-h)))=1/3*h</f>
				<br/>
				<f>int(x,a,b,l[1](x))=int(x,a,b,((x-x[0])*(x-x[2]))/((x[1]-x[0])*(x[1]-x[2])))=int(x,a,(a+h),((x-a)*(x-(a+h)))/(h/2*(-h/2)))=4/3*h</f>
				<br/>
				<f>int(x,a,b,l[2](x))=int(x,a,b,((x-x[0])*(x-x[1]))/((x[2]-x[0])*(x[2]-x[1])))=int(x,a,(a+h),((x-a)*(x-(a+h/2)))/((h)*(h/2)))=1/3*h</f>
				<br/>
				<f>int(x,a,b,f(x))=int(x,a,b,p[2](x))=int(x,a,b,(sum(i,0,2,f(x[i])*l[i](x))))=sum(i,0,2,(f(x[i])*int(x,a,b,l[i](x))))</f>
			</description>
			<layout>
				<row perc="50">
					<col perc="40" name="integ"/>
					<col perc="10" name="integV"/>
					<col perc="40" name="trap"/>
					<col perc="10" name="trapV"/>
				</row>
				<row perc="50">
					<col perc="40" name="simp"/>
					<col perc="10" name="simpV"/>
					<col perc="40" name="bool"/>
					<col perc="10" name="boolV"/>
				</row>
			</layout>
			<seq>
				<script>
			        expand( left = false; right = false );
			        deleteAll();
			        integ.setTitle( title = "Integral" );
			        trap.setTitle( title = "Trapez-Regel" );
			        simp.setTitle( title = "Simpson-Regel" );
			        bool.setTitle( title = "Boole-Regel" );
			        newObject( def = integ.xMin := -1);
			        newObject( def = trap.xMin := integ.xMin);
			        newObject( def = simp.xMin := integ.xMin);
			        newObject( def = bool.xMin := integ.xMin);
			        newObject( def = integ.xMax := 9);
			        newObject( def = trap.xMax := integ.xMax);
			        newObject( def = simp.xMax := integ.xMax);
			        newObject( def = bool.xMax := integ.xMax);
			        newObject( def = integ.yMin := -1.5);
			        newObject( def = trap.yMin := integ.yMin);
			        newObject( def = simp.yMin := integ.yMin);
			        newObject( def = bool.yMin := integ.yMin);
			        newObject( def = integ.yMax := 7);
			        newObject( def = trap.yMax := integ.yMax);
			        newObject( def = simp.yMax := integ.yMax);
			        newObject( def = bool.yMax := integ.yMax);
			        newObject( def = a:= punkt( 1, -0.7*1 ); target = integ );
			        newObject( def = b:= punkt( 7, -0.7*1 ); target = integ );
			        newObject( def = vy := vektor( {0,1}) );
			        newObject( def = ag:= gerade( a, vy ); target = integ );
			        trap.addGraph( name = ag );
			        simp.addGraph( name = ag );
			        bool.addGraph( name = ag );
			         newObject( def = bg:= gerade( b, vy ); target = integ );
			        trap.addGraph( name = bg );
			        simp.addGraph( name = bg );
			        bool.addGraph( name = bg );
			        newObject( def = ax := a.x );
			        newObject( def = bx := b.x );
			        newObject( def = f(x):=2+sin(2*sin(x)+2*x); target = integ);
			        trap.addGraph( name = f );
			        bool.addGraph( name = f );
			        	newObject( def = intfl:=flaeche({punkt(ax,0),punkt(bx,0),kurve(t,bx,ax,t,f(t))}); color = gray; target = integ; hide = true );
			        	newObject( def = h := (bx - ax)/4 );
                     newObject( def = xpos(i) := ax + i*h );
			        	newObject( def = sxg1 := gerade( punkt( xpos(1), 0 ) , vy ); linestyle = dash; target = trap );
			        	newObject( def = sxg2 := gerade( punkt( xpos(2), 0 ) , vy ); linestyle = dash; target = trap );
			        	newObject( def = sxg3 := gerade( punkt( xpos(3), 0 ) , vy ); linestyle = dash; target = trap );
			        	newObject( def = trapfl:=flaeche({punkt(ax,0),punkt(ax,f(ax)),punkt(xpos(1),f(xpos(1) )),punkt(xpos(2),f(xpos(2) )),punkt(xpos(3),f(xpos(3) )),punkt(xpos(4),f(xpos(4)) ),punkt(xpos(4),0 ) }); color = blue; target = trap; hide = true );
newObject( def = boolM := matrix(i,5,k,5, xpos(i-1)^(k-1) ); );
newObject( def = boolB := vektor(k,5,f(xpos(k-1) ))) ;
newObject( def = boolK := solvelin(boolM, boolB ) );
newObject( def = boolPoly(x):= sum(i,1,5, boolK[i]*x^(i-1) ) ; color = red; target = bool );
newObject( def = boolfl:=flaeche({punkt(ax,0),punkt(bx,0),kurve(t,bx,ax,t,boolPoly(t))}); color = red; target = bool; hide = true );
newObject( def = simpM1 := matrix(i,3,k,3, xpos(i-1)^(k-1) ); );
newObject( def = simpB1 := vektor(k,3,f(xpos(k-1) ))) ;
newObject( def = simpK1 := solvelin(simpM1, simpB1 ) );
newObject( def = simpPoly1(x):= sum(i,1,3, simpK1[i]*x^(i-1) ) ; color = cyan; target = simp );
newObject( def = simpfl1:=flaeche({punkt(ax,0),punkt(xpos(2),0),kurve(t,xpos(2),ax,t,simpPoly1(t))}); color = cyan; target = simp; hide = true );

newObject( def = simpM2 := matrix(i,3,k,3, xpos(i+1)^(k-1) ); );
newObject( def = simpB2 := vektor(k,3,f(xpos(k+1) ))) ;
newObject( def = simpK2 := solvelin(simpM2, simpB2 ) );
newObject( def = simpPoly2(x):= sum(i,1,3, simpK2[i]*x^(i-1) ) ; color = magenta; target = simp );
newObject( def = simpfl2:=flaeche({punkt(xpos(2),0),punkt(bx,0),kurve(t,bx, xpos(2),t,simpPoly2(t))}); color = magenta; target = simp; hide = true );
simp.addGraph( name = f );
simp.addGraph( name = sxg2 );




			        

			         

			        
			        
			   </script>
			</seq>
		</step>
		<step>
			<description>Wir ersetzen <f>f(x)=p[3](x)</f>, schreiben das Interpolationspolynom mit Hilfe der entsprechenden Lagrange-Faktoren <f>p[3](x)=f(x[0])*l[0](x)+f(x[1])*l[1](x)+f(x[2])*l[2](x)+f(x[3])*l[3](x)</f>,
		<br/>erhalten für das Integral <f>int(x,a,b,f(x))=f(x[0])*int(x,a,b,l[0](x))+f(x[1])*int(x,a,b,l[1](x))+f(x[2])*int(x,a,b,l[2](x))+f(x[3])*int(x,a,b,l[3](x))</f>,
		<br/>
				<f>int(x,a,b,l[0](x))=3/8*h=int(x,a,b,l[3](x))</f> und  <f>int(x,a,b,l[1](x))=9/8*h=int(x,a,b,l[2](x))</f>
				<br/>nach der Integration über die Lagrange-Faktoren die Quadratur-Formel: 
		<br/>
				<strong>3/8-Regel</strong>
				<f>Q[3](f)=f(x[0])*3/8*h+f(x[1])*9/8*h+f(x[2])*9/8*h+f(x[3])*3/8*h</f>
			</description>
		</step>
		<step>
			<description>
				<table>
					<tr>
						<td>Name</td>
						<td>Quadratur-Formel</td>
					</tr>
					<tr>
						<td>Trapez-Regel</td>
						<td>
							<f>Q[1](f)=h/2*(f(x[0])+f(x[1]))</f>
						</td>
					</tr>
					<tr>
						<td>Simpson-Regel</td>
						<td>
							<f>Q[2](f)=h/3*(f(x[0])+4*f(x[1])+f(x[2]))</f>
						</td>
					</tr>
					<tr>
						<td>3/8-Regel</td>
						<td>
							<f>Q[3](f)=(3*h)/8*(f(x[0])+3*f(x[1])+3*f(x[2])+f(x[3]))</f>
						</td>
					</tr>
					<tr>
						<td>Boole-Regel</td>
						<td>
							<f>Q[4](f)=(2*h)/45*(7*f(x[0])+32*f(x[1])+12*f(x[2])+32*f(x[3])+7*f(x[4]))</f>
						</td>
					</tr>
				</table>
			</description>
		</step>
	</body>
</math4u2>

=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/doc/hilfe/03Objekte/03.04.11Pfeil.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE math4u2 PUBLIC "-//FH Augsburg//DTD Math4u2//DE" "http://www.math4u2.de/xml/dtd/math4u2DTD.dtd">
<math4u2>
	<head>
		<version>2.0</version>
		<author>Stefan Fenn, Erich Seifert, Prof. Dr. Maximilian Weiß</author>
		<module id="main" class="ShowMeGraph"/>
	</head>
	<body>
		<location>3. Daten, Funktionen, Objekte, Graphen/3.4 Affine Objekte</location>
		<title>3.4.11 Pfeil</title>
		<step>
			<title>3.4.11 Pfeil</title>
			<description>
Ein Pfeil ist ein Repräsentant eines zweidimensionalen Vektors <code>v</code>. Neben diesem Vektor ist zu seiner
Definition noch ein Aufpunkt erforderlich.							

<p/><strong>Pfeil definieren</strong>
<br/>Ein Pfeil wird definiert wie:
<br/><code>pf:=pfeil(punkt(2,-1),vektor({1.5,1}))</code>.
<p/>Hat man einen Vektor <code>vek:=vektor({1,-3})</code> definiert, so erhält man mit 
<br/><code>pf1:=pfeil(punkt(1,1),vek)</code> und <code>pf2:=pfeil(punkt(1,3),vek)</code>
<br/>zwei Repräsentanten des einen Vektors <code>vek</code>, also zwei parallelgleiche Pfeile.

<p/><strong>Detailsicht</strong>
<p/><img src="math4u2/doc/images/objekte/pfeil-detail01.jpg"/>

<p/><strong>Pfeil mit der Maus verändern</strong>
<br/>Wenn ein Pfeil <code>pf1</code> auf der Zeichenebene dargestellt 
wird, dann kann man seine Spitze mit der Maus bewegen und so die 
Komponenten des zugehörigen Vektors <code>vek</code> verändern.
Alle anderen Repräsentanten des Vektors <code>vek</code> verändern sich 
dann parallelgleich.

<p/><strong>Methoden eines Pfeils</strong>
<br/>Zu einem Pfeil pf1 liefert
<br/><code>pf1.start   </code><tab/> den Aufpunkt und
<br/><code>pf1.richtung</code><tab/> die Richtung des Pfeils, also den Vektor, den der Pfeil repräsentiert.

<p/><strong>Beispiel:</strong> Vektor mit zwei Repräsentanten
<p/><img src="math4u2/doc/images/objekte/pfeil01.jpg"/>
			</description>
		</step>
	</body>
</math4u2>

=== fennstef/math4u2/de.math4u2.application/src/main/resources/math4u2/doc/hilfe/02Bedienung/02.01.05Lektionen-Fenster.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE math4u2 PUBLIC "-//FH Augsburg//DTD Math4u2//DE" "http://www.math4u2.de/xml/dtd/math4u2DTD.dtd">
<math4u2>
	<head>
		<version>2.0</version>
		<author>Stefan Fenn, Erich Seifert, Prof. Dr. Maximilian Weiﬂ</author>
		<module id="main" class="ShowMeGraph"/>
	</head>
	<body>
		<location>2. Bedienung</location>
		<title>2.1.5 Lektionen-Fenster</title>
		<step>
			<title>2.1.5 Lektionen-Fenster</title>
			<description>
Mehr dazu im Abschnitt 2.6 dieses Kapitels.
			</description>
		</step>
	</body>
</math4u2>
